In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Titanic-Dataset.csv")

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.shape

(891, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.isnull().sum()[df.isnull().sum()>0]

Age         177
Cabin       687
Embarked      2
dtype: int64

In [ ]:
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [ ]:
df[df.columns[df.isnull().any()]]

      Age Cabin Embarked
0    22.0   NaN        S
1    38.0   C85        C
2    26.0   NaN        S
3    35.0  C123        S
4    35.0   NaN        S
..    ...   ...      ...
886  27.0   NaN        S
887  19.0   B42        S
888   NaN   NaN        S
889  26.0  C148        C
890  32.0   NaN        Q

[891 rows x 3 columns]

In [ ]:
df.isnull().sum()/891*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [ ]:
df[df['Age'].isnull()==False]['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
885    39.0
886    27.0
887    19.0
889    26.0
890    32.0
Name: Age, Length: 714, dtype: float64

In [ ]:
df[df['Age'].isnull()==True]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df[df['Age'].isnull()==False][['Sex','Age']].groupby('Sex').mean()

              Age
Sex
female  27.915709
male    30.726645

In [ ]:
df[df['Age'].isnull()==False][['Pclass','Age']].groupby('Pclass').mean()

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

In [ ]:
import numpy as np

In [ ]:
data = {
    'Student_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', np.nan, np.nan],
    'Age': [21, np.nan, 23, 22, np.nan, 24, np.nan, np.nan],
    'Department': ['CS', 'IT', np.nan, 'ECE', 'ME', 'CS', np.nan, np.nan],
    'Marks': [85, 90, np.nan, 75, 88, np.nan, np.nan, np.nan],
    'Attendance': [92, np.nan, 85, 80, 95, 88, np.nan, np.nan]
}

In [ ]:
df2 = pd.DataFrame(data)

In [ ]:
df2

   Student_ID     Name   Age Department  Marks  Attendance
0         101    Alice  21.0         CS   85.0        92.0
1         102      Bob   NaN         IT   90.0         NaN
2         103  Charlie  23.0        NaN    NaN        85.0
3         104    David  22.0        ECE   75.0        80.0
4         105      Eva   NaN         ME   88.0        95.0
5         106    Frank  24.0         CS    NaN        88.0
6         107      NaN   NaN        NaN    NaN         NaN
7         108      NaN   NaN        NaN    NaN         NaN

In [ ]:
df2.isnull().sum()

Student_ID    0
Name          2
Age           4
Department    3
Marks         4
Attendance    3
dtype: int64

remove rows if it has any null value

In [ ]:
df2.dropna()

   Student_ID   Name   Age Department  Marks  Attendance
0         101  Alice  21.0         CS   85.0        92.0
3         104  David  22.0        ECE   75.0        80.0

In [ ]:
df2

   Student_ID     Name   Age Department  Marks  Attendance
0         101    Alice  21.0         CS   85.0        92.0
1         102      Bob   NaN         IT   90.0         NaN
2         103  Charlie  23.0        NaN    NaN        85.0
3         104    David  22.0        ECE   75.0        80.0
4         105      Eva   NaN         ME   88.0        95.0
5         106    Frank  24.0         CS    NaN        88.0
6         107      NaN   NaN        NaN    NaN         NaN
7         108      NaN   NaN        NaN    NaN         NaN

In [ ]:
df2 = df2.dropna()

In [ ]:
df2

   Student_ID   Name   Age Department  Marks  Attendance
0         101  Alice  21.0         CS   85.0        92.0
3         104  David  22.0        ECE   75.0        80.0

In [ ]:
data = {
    'Student_ID': [101, 102, 103, 104, 105, 106, 107, 108, np.nan],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', np.nan, np.nan, np.nan],
    'Age': [21, np.nan, 23, 22, np.nan, 24, np.nan, np.nan, np.nan],
    'Department': ['CS', 'IT', np.nan, 'ECE', 'ME', 'CS', np.nan, np.nan, np.nan],
    'Marks': [85, 90, np.nan, 75, 88, np.nan, np.nan, np.nan, np.nan],
    'Attendance': [92, np.nan, 85, 80, 95, 88, np.nan, np.nan, np.nan]
}

In [ ]:
df3 = pd.DataFrame(data)
df3

   Student_ID     Name   Age Department  Marks  Attendance
0       101.0    Alice  21.0         CS   85.0        92.0
1       102.0      Bob   NaN         IT   90.0         NaN
2       103.0  Charlie  23.0        NaN    NaN        85.0
3       104.0    David  22.0        ECE   75.0        80.0
4       105.0      Eva   NaN         ME   88.0        95.0
5       106.0    Frank  24.0         CS    NaN        88.0
6       107.0      NaN   NaN        NaN    NaN         NaN
7       108.0      NaN   NaN        NaN    NaN         NaN
8         NaN      NaN   NaN        NaN    NaN         NaN

In [ ]:
df3.dropna(how='all')

   Student_ID     Name   Age Department  Marks  Attendance
0       101.0    Alice  21.0         CS   85.0        92.0
1       102.0      Bob   NaN         IT   90.0         NaN
2       103.0  Charlie  23.0        NaN    NaN        85.0
3       104.0    David  22.0        ECE   75.0        80.0
4       105.0      Eva   NaN         ME   88.0        95.0
5       106.0    Frank  24.0         CS    NaN        88.0
6       107.0      NaN   NaN        NaN    NaN         NaN
7       108.0      NaN   NaN        NaN    NaN         NaN

In [ ]:
df3 = df3.dropna(how='all')

In [ ]:
df3.dropna(thresh=3)

   Student_ID     Name   Age Department  Marks  Attendance
0       101.0    Alice  21.0         CS   85.0        92.0
1       102.0      Bob   NaN         IT   90.0         NaN
2       103.0  Charlie  23.0        NaN    NaN        85.0
3       104.0    David  22.0        ECE   75.0        80.0
4       105.0      Eva   NaN         ME   88.0        95.0
5       106.0    Frank  24.0         CS    NaN        88.0

In [ ]:
df3.dropna(thresh=5)

   Student_ID   Name   Age Department  Marks  Attendance
0       101.0  Alice  21.0         CS   85.0        92.0
3       104.0  David  22.0        ECE   75.0        80.0
4       105.0    Eva   NaN         ME   88.0        95.0
5       106.0  Frank  24.0         CS    NaN        88.0

In [ ]:
df3.dropna(thresh=6)

   Student_ID   Name   Age Department  Marks  Attendance
0       101.0  Alice  21.0         CS   85.0        92.0
3       104.0  David  22.0        ECE   75.0        80.0

In [ ]:
data = {
    'Customer_ID': [101, 102, 103, 104, 105, 106, 107, 108, np.nan],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', np.nan, np.nan, np.nan],
    'Age': [21, np.nan, 23, 22, np.nan, 24, np.nan, np.nan, np.nan],
    'Department': ['CS', 'IT', np.nan, 'ECE', 'ME', 'CS', np.nan, np.nan, np.nan],
    'Salary': [85, 90, np.nan, 75, 88, np.nan, np.nan, np.nan, np.nan],
    'Cibil': [850, np.nan, 845, 680, 795, 588, np.nan, np.nan, np.nan]
}

In [ ]:
df4 = pd.DataFrame(data)
df4

   Customer_ID     Name   Age Department  Salary  Cibil
0        101.0    Alice  21.0         CS    85.0  850.0
1        102.0      Bob   NaN         IT    90.0    NaN
2        103.0  Charlie  23.0        NaN     NaN  845.0
3        104.0    David  22.0        ECE    75.0  680.0
4        105.0      Eva   NaN         ME    88.0  795.0
5        106.0    Frank  24.0         CS     NaN  588.0
6        107.0      NaN   NaN        NaN     NaN    NaN
7        108.0      NaN   NaN        NaN     NaN    NaN
8          NaN      NaN   NaN        NaN     NaN    NaN

In [ ]:
df4.dropna(subset=['Cibil'])

   Customer_ID     Name   Age Department  Salary  Cibil
0        101.0    Alice  21.0         CS    85.0  850.0
2        103.0  Charlie  23.0        NaN     NaN  845.0
3        104.0    David  22.0        ECE    75.0  680.0
4        105.0      Eva   NaN         ME    88.0  795.0
5        106.0    Frank  24.0         CS     NaN  588.0

In [ ]:
df4.dropna(subset=['Salary'])

   Customer_ID   Name   Age Department  Salary  Cibil
0        101.0  Alice  21.0         CS    85.0  850.0
1        102.0    Bob   NaN         IT    90.0    NaN
3        104.0  David  22.0        ECE    75.0  680.0
4        105.0    Eva   NaN         ME    88.0  795.0

In [ ]:
df4.dropna(subset=['Cibil','Salary'])

   Customer_ID   Name   Age Department  Salary  Cibil
0        101.0  Alice  21.0         CS    85.0  850.0
3        104.0  David  22.0        ECE    75.0  680.0
4        105.0    Eva   NaN         ME    88.0  795.0

In [ ]:
df4.shape

(9, 6)

In [ ]:
data = {
    'Customer_ID': [101, 102, 103, 104, 105, 106, 107, 108, np.nan],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', np.nan, np.nan, np.nan],
    'Age': [21, np.nan, 23, 22, np.nan, 24, np.nan, np.nan, np.nan],
    'Department': ['CS', 'IT', np.nan, 'ECE', 'ME', 'CS', np.nan, np.nan, np.nan],
    'Salary': [85, 90, np.nan, 75, 88, np.nan, np.nan, np.nan, np.nan],
    'Cibil': [850, np.nan, 845, 680, 795, 588, np.nan, np.nan, np.nan],
    'NoOfLoan': [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan]
}
df5 = pd.DataFrame(data)

In [ ]:
df5

   Customer_ID     Name   Age Department  Salary  Cibil  NoOfLoan
0        101.0    Alice  21.0         CS    85.0  850.0       NaN
1        102.0      Bob   NaN         IT    90.0    NaN       NaN
2        103.0  Charlie  23.0        NaN     NaN  845.0       NaN
3        104.0    David  22.0        ECE    75.0  680.0       NaN
4        105.0      Eva   NaN         ME    88.0  795.0       NaN
5        106.0    Frank  24.0         CS     NaN  588.0       NaN
6        107.0      NaN   NaN        NaN     NaN    NaN       NaN
7        108.0      NaN   NaN        NaN     NaN    NaN       NaN
8          NaN      NaN   NaN        NaN     NaN    NaN       NaN

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  8 non-null      float64
 1   Name         6 non-null      object
 2   Age          4 non-null      float64
 3   Department   5 non-null      object
 4   Salary       4 non-null      float64
 5   Cibil        5 non-null      float64
 6   NoOfLoan     0 non-null      float64
dtypes: float64(5), object(2)
memory usage: 636.0+ bytes

In [ ]:
df5.drop(columns=['NoOfLoan'])

   Customer_ID     Name   Age Department  Salary  Cibil
0        101.0    Alice  21.0         CS    85.0  850.0
1        102.0      Bob   NaN         IT    90.0    NaN
2        103.0  Charlie  23.0        NaN     NaN  845.0
3        104.0    David  22.0        ECE    75.0  680.0
4        105.0      Eva   NaN         ME    88.0  795.0
5        106.0    Frank  24.0         CS     NaN  588.0
6        107.0      NaN   NaN        NaN     NaN    NaN
7        108.0      NaN   NaN        NaN     NaN    NaN
8          NaN      NaN   NaN        NaN     NaN    NaN

In [ ]:
df5.drop(columns=['NoOfLoan'],axis=1)

   Customer_ID     Name   Age Department  Salary  Cibil
0        101.0    Alice  21.0         CS    85.0  850.0
1        102.0      Bob   NaN         IT    90.0    NaN
2        103.0  Charlie  23.0        NaN     NaN  845.0
3        104.0    David  22.0        ECE    75.0  680.0
4        105.0      Eva   NaN         ME    88.0  795.0
5        106.0    Frank  24.0         CS     NaN  588.0
6        107.0      NaN   NaN        NaN     NaN    NaN
7        108.0      NaN   NaN        NaN     NaN    NaN
8          NaN      NaN   NaN        NaN     NaN    NaN

In [ ]:
df5

   Customer_ID     Name   Age Department  Salary  Cibil  NoOfLoan
0        101.0    Alice  21.0         CS    85.0  850.0       NaN
1        102.0      Bob   NaN         IT    90.0    NaN       NaN
2        103.0  Charlie  23.0        NaN     NaN  845.0       NaN
3        104.0    David  22.0        ECE    75.0  680.0       NaN
4        105.0      Eva   NaN         ME    88.0  795.0       NaN
5        106.0    Frank  24.0         CS     NaN  588.0       NaN
6        107.0      NaN   NaN        NaN     NaN    NaN       NaN
7        108.0      NaN   NaN        NaN     NaN    NaN       NaN
8          NaN      NaN   NaN        NaN     NaN    NaN       NaN

In [ ]:
df5.dropna(subset=['Age'],axis=0)

   Customer_ID     Name   Age Department  Salary  Cibil  NoOfLoan
0        101.0    Alice  21.0         CS    85.0  850.0       NaN
2        103.0  Charlie  23.0        NaN     NaN  845.0       NaN
3        104.0    David  22.0        ECE    75.0  680.0       NaN
5        106.0    Frank  24.0         CS     NaN  588.0       NaN

In [ ]:
df5.dropna(subset=['Age'],inplace=True)

In [ ]:
df5

   Customer_ID     Name   Age Department  Salary  Cibil  NoOfLoan
0        101.0    Alice  21.0         CS    85.0  850.0       NaN
2        103.0  Charlie  23.0        NaN     NaN  845.0       NaN
3        104.0    David  22.0        ECE    75.0  680.0       NaN
5        106.0    Frank  24.0         CS     NaN  588.0       NaN

In [ ]:
data = {
    'Customer_ID': [101, 102, 103, 104, 105, 106, 107, 108, np.nan],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', np.nan, np.nan, np.nan],
    'Age': [21, np.nan, 23, 22, np.nan, 24, np.nan, np.nan, np.nan],
    'Department': ['CS', 'IT', np.nan, 'ECE', 'ME', 'CS', np.nan, np.nan, np.nan],
    'Salary': [85, 90, np.nan, 75, 88, np.nan, np.nan, np.nan, np.nan],
    'Cibil': [850, np.nan, 845, 680, 795, 588, np.nan, np.nan, np.nan],
    'NoOfLoan': [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan]
}
df6 = pd.DataFrame(data)

In [ ]:
df7 = df6.dropna(thresh=3,inplace=True)

In [ ]:
df6

   Customer_ID     Name   Age Department  Salary  Cibil  NoOfLoan
0        101.0    Alice  21.0         CS    85.0  850.0       NaN
1        102.0      Bob   NaN         IT    90.0    NaN       NaN
2        103.0  Charlie  23.0        NaN     NaN  845.0       NaN
3        104.0    David  22.0        ECE    75.0  680.0       NaN
4        105.0      Eva   NaN         ME    88.0  795.0       NaN
5        106.0    Frank  24.0         CS     NaN  588.0       NaN

FFill & Bfill()

In [ ]:
df = pd.DataFrame({
    'Date': pd.date_range('2026-01-01', periods=10),
    'Temperature': [30,31,np.nan,33,34,np.nan,35,36,np.nan,39]
})

In [ ]:
df

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03          NaN
3 2026-01-04         33.0
4 2026-01-05         34.0
5 2026-01-06          NaN
6 2026-01-07         35.0
7 2026-01-08         36.0
8 2026-01-09          NaN
9 2026-01-10         39.0

In [ ]:
df.ffill()

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03         31.0
3 2026-01-04         33.0
4 2026-01-05         34.0
5 2026-01-06         34.0
6 2026-01-07         35.0
7 2026-01-08         36.0
8 2026-01-09         36.0
9 2026-01-10         39.0

In [ ]:
df

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03          NaN
3 2026-01-04         33.0
4 2026-01-05         34.0
5 2026-01-06          NaN
6 2026-01-07         35.0
7 2026-01-08         36.0
8 2026-01-09          NaN
9 2026-01-10         39.0

In [ ]:
df = pd.DataFrame({
    'Date': pd.date_range('2026-01-01', periods=10),
    'Temperature': [np.nan,31,np.nan,33,34,np.nan,35,36,np.nan,31]
})

In [ ]:
df.ffill()

        Date  Temperature
0 2026-01-01          NaN
1 2026-01-02         31.0
2 2026-01-03         31.0
3 2026-01-04         33.0
4 2026-01-05         34.0
5 2026-01-06         34.0
6 2026-01-07         35.0
7 2026-01-08         36.0
8 2026-01-09         36.0
9 2026-01-10         31.0

In [ ]:
df = pd.DataFrame({
    'Date': pd.date_range('2026-01-01', periods=10),
    'Temperature': [30,31,np.nan,np.nan,33,34,np.nan,35,36,np.nan]
})

df

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03          NaN
3 2026-01-04          NaN
4 2026-01-05         33.0
5 2026-01-06         34.0
6 2026-01-07          NaN
7 2026-01-08         35.0
8 2026-01-09         36.0
9 2026-01-10          NaN

In [ ]:
df.bfill()

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03         33.0
3 2026-01-04         33.0
4 2026-01-05         33.0
5 2026-01-06         34.0
6 2026-01-07         35.0
7 2026-01-08         35.0
8 2026-01-09         36.0
9 2026-01-10          NaN

In [ ]:
df.bfill(inplace=True)

In [ ]:
df

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03         33.0
3 2026-01-04         33.0
4 2026-01-05         33.0
5 2026-01-06         34.0
6 2026-01-07         35.0
7 2026-01-08         35.0
8 2026-01-09         36.0
9 2026-01-10          NaN

In [ ]:
df = pd.DataFrame({
    'Date': pd.date_range('2026-01-01', periods=10),
    'Temperature': [30,31,np.nan,np.nan,np.nan,34,np.nan,35,36,np.nan]
})

df
df.ffill(limit=2)

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03         31.0
3 2026-01-04         31.0
4 2026-01-05          NaN
5 2026-01-06         34.0
6 2026-01-07         34.0
7 2026-01-08         35.0
8 2026-01-09         36.0
9 2026-01-10         36.0

In [ ]:
df = pd.DataFrame({
    'Date': pd.date_range('2026-01-01', periods=10),
    'Temperature': [30,31,np.nan,np.nan,np.nan,34,np.nan,35,36,np.nan]
})

df
df.bfill(limit=2)

        Date  Temperature
0 2026-01-01         30.0
1 2026-01-02         31.0
2 2026-01-03          NaN
3 2026-01-04         34.0
4 2026-01-05         34.0
5 2026-01-06         34.0
6 2026-01-07         35.0
7 2026-01-08         35.0
8 2026-01-09         36.0
9 2026-01-10          NaN

In [ ]:
data = {
    'Customer_ID': [101, 102, 103, 104, 105, 106, 107, 108, np.nan],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', np.nan, np.nan, np.nan],
    'Age': [21, np.nan, 23, 22, np.nan, 24, np.nan, np.nan, np.nan],
    'Department': ['CS', 'IT', np.nan, 'ECE', 'ME', 'CS', np.nan, np.nan, np.nan],
    'Salary': [85, 90, np.nan, 75, 88, np.nan, np.nan, np.nan, np.nan],
    'Cibil': [850, np.nan, 845, 680, 795, 588, np.nan, np.nan, np.nan],
    'NoOfLoan': [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan]
}
df6 = pd.DataFrame(data)

In [ ]:
df6

   Customer_ID     Name   Age Department  Salary  Cibil  NoOfLoan
0        101.0    Alice  21.0         CS    85.0  850.0       NaN
1        102.0      Bob   NaN         IT    90.0    NaN       NaN
2        103.0  Charlie  23.0        NaN     NaN  845.0       NaN
3        104.0    David  22.0        ECE    75.0  680.0       NaN
4        105.0      Eva   NaN         ME    88.0  795.0       NaN
5        106.0    Frank  24.0         CS     NaN  588.0       NaN
6        107.0      NaN   NaN        NaN     NaN    NaN       NaN
7        108.0      NaN   NaN        NaN     NaN    NaN       NaN
8          NaN      NaN   NaN        NaN     NaN    NaN       NaN

In [ ]:
df6['Department'].ffill()

0     CS
1     IT
2     IT
3    ECE
4     ME
5     CS
6     CS
7     CS
8     CS
Name: Department, dtype: object

In [ ]:
df6['Department'] = df6['Department'].ffill()

In [ ]:
df6

   Customer_ID     Name   Age Department  Salary  Cibil  NoOfLoan
0        101.0    Alice  21.0         CS    85.0  850.0       NaN
1        102.0      Bob   NaN         IT    90.0    NaN       NaN
2        103.0  Charlie  23.0         IT     NaN  845.0       NaN
3        104.0    David  22.0        ECE    75.0  680.0       NaN
4        105.0      Eva   NaN         ME    88.0  795.0       NaN
5        106.0    Frank  24.0         CS     NaN  588.0       NaN
6        107.0      NaN   NaN         CS     NaN    NaN       NaN
7        108.0      NaN   NaN         CS     NaN    NaN       NaN
8          NaN      NaN   NaN         CS     NaN    NaN       NaN

In [ ]:
df6.to_csv("Employee_Dataset.csv")