# Data Cleaning

In [1]:
import pandas as pd
import numpy as np

## 1. Create a Messy Dataset

We intentionally introduce common real-world data-quality problems:
- duplicate rows
- extra spaces
- inconsistent capitalization
- inconsistent category labels
- inconsistent city names
- phone-number formatting differences
- dates stored as strings
- salary stored as text

In [2]:
data = {
    "Customer ID": [101, 102, 103, 103, 104, 105, 106, 107, 108, 109, 110, 110,103],
    "Customer Name": [
        " John Smith ", "PRIYA SHARMA", "arun kumar", "arun kumar",
        "  Meena Rao", "RAHUL DAS ", "sneha Iyer", "KARTHIK",
        "anita joseph ", None, "Vijay Kumar", "  priya sharma","arun kumar"
    ],
    "City": [
        "chennai", "Chennai ", "CHENNAI", "CHENNAI",
        "madras", " Salem", "SALEM", "Bangalore",
        "BENGALURU", "Chennai", " chennai ", "CHENNAI","CHENNAI"
    ],
    "Gender": [
        "Male", "female", "M", "M",
        "F", "MALE", "Female", "m",
        "FEMALE", "Female", "Male", "F","M"
    ],
    "Phone": [
        "+91-9876543210", "91-9876543211", "9876543212", "9876543212",
        "+91 9876543213", "987-654-3214", "9876543215", "91-9876543216",
        "+91-9876543217", "9876543218", None, "91-9876543219","9876543212"
    ],
    "Join Date": [
        "2024-01-15", "15/02/2024", "2024-03-10", "2024-03-10",
        "20/04/2024", "2024-05-05", "06/06/2024", "2024-07-15",
        "20/08/2024", None, "2024-10-01", "15/11/2024","2024-03-10"
    ],
    "Salary": [
        "50000", "60000", "55000", "55000",
        "70000", "48000", "62000", "58000",
        "65000", None, "72000", "60000","55000"
    ]
}

df = pd.DataFrame(data)
df

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,+91-9876543210,2024-01-15,50000
1,102,PRIYA SHARMA,Chennai,female,91-9876543211,15/02/2024,60000
2,103,arun kumar,CHENNAI,M,9876543212,2024-03-10,55000
3,103,arun kumar,CHENNAI,M,9876543212,2024-03-10,55000
4,104,Meena Rao,madras,F,+91 9876543213,20/04/2024,70000
5,105,RAHUL DAS,Salem,MALE,987-654-3214,2024-05-05,48000
6,106,sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,KARTHIK,Bangalore,m,91-9876543216,2024-07-15,58000
8,108,anita joseph,BENGALURU,FEMALE,+91-9876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
11,110,priya sharma,CHENNAI,F,91-9876543219,15/11/2024,60000
12,103,arun kumar,CHENNAI,M,9876543212,2024-03-10,55000

In [3]:
df.shape

(13, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    13 non-null     int64
 1   Customer Name  12 non-null     object
 2   City           13 non-null     object
 3   Gender         13 non-null     object
 4   Phone          12 non-null     object
 5   Join Date      12 non-null     object
 6   Salary         12 non-null     object
dtypes: int64(1), object(6)
memory usage: 860.0+ bytes

In [5]:
df.isnull().sum()

Customer ID      0
Customer Name    1
City             0
Gender           0
Phone            1
Join Date        1
Salary           1
dtype: int64

## Duplicates

In [6]:
df.duplicated()

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
dtype: bool

In [7]:
df[df.duplicated()]

    Customer ID Customer Name     City Gender       Phone   Join Date Salary
3           103    arun kumar  CHENNAI      M  9876543212  2024-03-10  55000
12          103    arun kumar  CHENNAI      M  9876543212  2024-03-10  55000

In [8]:
df[df.duplicated(keep='last')]

   Customer ID Customer Name     City Gender       Phone   Join Date Salary
2          103    arun kumar  CHENNAI      M  9876543212  2024-03-10  55000
3          103    arun kumar  CHENNAI      M  9876543212  2024-03-10  55000

In [9]:
df[df.duplicated(keep=False)]

    Customer ID Customer Name     City Gender       Phone   Join Date Salary
2           103    arun kumar  CHENNAI      M  9876543212  2024-03-10  55000
3           103    arun kumar  CHENNAI      M  9876543212  2024-03-10  55000
12          103    arun kumar  CHENNAI      M  9876543212  2024-03-10  55000

In [10]:
df.drop_duplicates()

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,+91-9876543210,2024-01-15,50000
1,102,PRIYA SHARMA,Chennai,female,91-9876543211,15/02/2024,60000
2,103,arun kumar,CHENNAI,M,9876543212,2024-03-10,55000
4,104,Meena Rao,madras,F,+91 9876543213,20/04/2024,70000
5,105,RAHUL DAS,Salem,MALE,987-654-3214,2024-05-05,48000
6,106,sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,KARTHIK,Bangalore,m,91-9876543216,2024-07-15,58000
8,108,anita joseph,BENGALURU,FEMALE,+91-9876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
11,110,priya sharma,CHENNAI,F,91-9876543219,15/11/2024,60000

In [11]:
df.drop_duplicates(keep='last')

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,+91-9876543210,2024-01-15,50000
1,102,PRIYA SHARMA,Chennai,female,91-9876543211,15/02/2024,60000
4,104,Meena Rao,madras,F,+91 9876543213,20/04/2024,70000
5,105,RAHUL DAS,Salem,MALE,987-654-3214,2024-05-05,48000
6,106,sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,KARTHIK,Bangalore,m,91-9876543216,2024-07-15,58000
8,108,anita joseph,BENGALURU,FEMALE,+91-9876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
11,110,priya sharma,CHENNAI,F,91-9876543219,15/11/2024,60000
12,103,arun kumar,CHENNAI,M,9876543212,2024-03-10,55000

In [12]:
df.drop_duplicates(keep=False)

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,+91-9876543210,2024-01-15,50000
1,102,PRIYA SHARMA,Chennai,female,91-9876543211,15/02/2024,60000
4,104,Meena Rao,madras,F,+91 9876543213,20/04/2024,70000
5,105,RAHUL DAS,Salem,MALE,987-654-3214,2024-05-05,48000
6,106,sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,KARTHIK,Bangalore,m,91-9876543216,2024-07-15,58000
8,108,anita joseph,BENGALURU,FEMALE,+91-9876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
11,110,priya sharma,CHENNAI,F,91-9876543219,15/11/2024,60000

In [13]:
df = df.drop_duplicates(keep='last')

In [14]:
df

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,+91-9876543210,2024-01-15,50000
1,102,PRIYA SHARMA,Chennai,female,91-9876543211,15/02/2024,60000
4,104,Meena Rao,madras,F,+91 9876543213,20/04/2024,70000
5,105,RAHUL DAS,Salem,MALE,987-654-3214,2024-05-05,48000
6,106,sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,KARTHIK,Bangalore,m,91-9876543216,2024-07-15,58000
8,108,anita joseph,BENGALURU,FEMALE,+91-9876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
11,110,priya sharma,CHENNAI,F,91-9876543219,15/11/2024,60000
12,103,arun kumar,CHENNAI,M,9876543212,2024-03-10,55000

### Sub-set

In [15]:
df.duplicated(subset=['Customer ID'])

0     False
1     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
dtype: bool

In [16]:
df[df.duplicated(subset=['Customer ID'])]

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
11,110,priya sharma,CHENNAI,F,91-9876543219,15/11/2024,60000

In [17]:
df[df.duplicated(subset=['Customer ID'],keep='last')]

    Customer ID Customer Name       City Gender Phone   Join Date Salary
10          110   Vijay Kumar   chennai    Male  None  2024-10-01  72000

In [18]:
df[df.duplicated(subset=['Customer ID'],keep=False)]

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
11,110,priya sharma,CHENNAI,F,91-9876543219,15/11/2024,60000

In [19]:
df = df.drop_duplicates(subset=['Customer ID'])

In [20]:
df

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,+91-9876543210,2024-01-15,50000
1,102,PRIYA SHARMA,Chennai,female,91-9876543211,15/02/2024,60000
4,104,Meena Rao,madras,F,+91 9876543213,20/04/2024,70000
5,105,RAHUL DAS,Salem,MALE,987-654-3214,2024-05-05,48000
6,106,sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,KARTHIK,Bangalore,m,91-9876543216,2024-07-15,58000
8,108,anita joseph,BENGALURU,FEMALE,+91-9876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
12,103,arun kumar,CHENNAI,M,9876543212,2024-03-10,55000

## Strip()
remove whitespace at the beginning and end of a value

In [21]:
df['City']

0       chennai
1      Chennai
4        madras
5         Salem
6         SALEM
7     Bangalore
8     BENGALURU
9       Chennai
10     chennai
12      CHENNAI
Name: City, dtype: object

In [22]:
value = df['City'].unique().tolist()

In [23]:
value

['chennai',
 'Chennai ',
 'madras',
 ' Salem',
 'SALEM',
 'Bangalore',
 'BENGALURU',
 'Chennai',
 ' chennai ',
 'CHENNAI']

In [24]:
for i in value:
  print(len(i),":",i)

7 : chennai
8 : Chennai
6 : madras
6 :  Salem
5 : SALEM
9 : Bangalore
9 : BENGALURU
7 : Chennai
9 :  chennai
7 : CHENNAI

In [25]:
df['City'] = df['City'].str.strip()

/tmp/ipykernel_11730/482149319.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City'] = df['City'].str.strip()

In [26]:
df

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,+91-9876543210,2024-01-15,50000
1,102,PRIYA SHARMA,Chennai,female,91-9876543211,15/02/2024,60000
4,104,Meena Rao,madras,F,+91 9876543213,20/04/2024,70000
5,105,RAHUL DAS,Salem,MALE,987-654-3214,2024-05-05,48000
6,106,sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,KARTHIK,Bangalore,m,91-9876543216,2024-07-15,58000
8,108,anita joseph,BENGALURU,FEMALE,+91-9876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
12,103,arun kumar,CHENNAI,M,9876543212,2024-03-10,55000

In [27]:
value = df['City'].unique().tolist()
for i in value:
  print(len(i),":",i)

7 : chennai
7 : Chennai
6 : madras
5 : Salem
5 : SALEM
9 : Bangalore
9 : BENGALURU
7 : CHENNAI

In [32]:
for i in df.select_dtypes(include='object').columns.tolist():
  df[i] = df[i].str.strip()

/tmp/ipykernel_11730/2756853187.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i] = df[i].str.strip()

In [34]:
df1 = df.copy()

In [35]:
df1

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,+91-9876543210,2024-01-15,50000
1,102,PRIYA SHARMA,Chennai,female,91-9876543211,15/02/2024,60000
4,104,Meena Rao,madras,F,+91 9876543213,20/04/2024,70000
5,105,RAHUL DAS,Salem,MALE,987-654-3214,2024-05-05,48000
6,106,sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,KARTHIK,Bangalore,m,91-9876543216,2024-07-15,58000
8,108,anita joseph,BENGALURU,FEMALE,+91-9876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
12,103,arun kumar,CHENNAI,M,9876543212,2024-03-10,55000

## Capitalization

In [40]:
df1['Customer Name'].str.lower()

0       john smith
1     priya sharma
4        meena rao
5        rahul das
6       sneha iyer
7          karthik
8     anita joseph
9             None
10     vijay kumar
12      arun kumar
Name: Customer Name, dtype: object

In [41]:
df1['Customer Name'].str.upper()

0       JOHN SMITH
1     PRIYA SHARMA
4        MEENA RAO
5        RAHUL DAS
6       SNEHA IYER
7          KARTHIK
8     ANITA JOSEPH
9             None
10     VIJAY KUMAR
12      ARUN KUMAR
Name: Customer Name, dtype: object

In [39]:
df1['Customer Name'].str.title()

0       John Smith
1     Priya Sharma
4        Meena Rao
5        Rahul Das
6       Sneha Iyer
7          Karthik
8     Anita Joseph
9             None
10     Vijay Kumar
12      Arun Kumar
Name: Customer Name, dtype: object

In [42]:
df1['Customer Name'] = df1['Customer Name'].str.title()

In [43]:
df1

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,+91-9876543210,2024-01-15,50000
1,102,Priya Sharma,Chennai,female,91-9876543211,15/02/2024,60000
4,104,Meena Rao,madras,F,+91 9876543213,20/04/2024,70000
5,105,Rahul Das,Salem,MALE,987-654-3214,2024-05-05,48000
6,106,Sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,Karthik,Bangalore,m,91-9876543216,2024-07-15,58000
8,108,Anita Joseph,BENGALURU,FEMALE,+91-9876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
12,103,Arun Kumar,CHENNAI,M,9876543212,2024-03-10,55000

## Replace

In [44]:
df['Phone'].str.replace('-','')

0      +919876543210
1       919876543211
4     +91 9876543213
5         9876543214
6         9876543215
7       919876543216
8      +919876543217
9         9876543218
10              None
12        9876543212
Name: Phone, dtype: object

In [45]:
df['Phone'].str.replace(' ','')

0     +91-9876543210
1      91-9876543211
4      +919876543213
5       987-654-3214
6         9876543215
7      91-9876543216
8     +91-9876543217
9         9876543218
10              None
12        9876543212
Name: Phone, dtype: object

In [51]:
df1['Phone'] = (df1['Phone'].str.replace(' ','').str.replace('-','').str.replace('+',''))

In [55]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 12
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    10 non-null     int64
 1   Customer Name  9 non-null      object
 2   City           10 non-null     object
 3   Gender         10 non-null     object
 4   Phone          9 non-null      object
 5   Join Date      9 non-null      object
 6   Salary         9 non-null      object
dtypes: int64(1), object(6)
memory usage: 640.0+ bytes

## Contains - To filter

In [56]:
df1['Gender'].unique()

array(['Male', 'female', 'F', 'MALE', 'Female', 'm', 'FEMALE', 'M'],
      dtype=object)

In [57]:
df1[df1['Gender']=='Male']

    Customer ID Customer Name     City Gender         Phone   Join Date Salary
0           101    John Smith  chennai   Male  919876543210  2024-01-15  50000
10          110   Vijay Kumar  chennai   Male          None  2024-10-01  72000

In [63]:
df1.isnull().sum()

Customer ID      0
Customer Name    1
City             0
Gender           0
Phone            1
Join Date        1
Salary           1
dtype: int64

In [61]:
df1[df1['Gender'].str.contains('al',case=False,na=False)]

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,919876543210,2024-01-15,50000
1,102,Priya Sharma,Chennai,female,919876543211,15/02/2024,60000
5,105,Rahul Das,Salem,MALE,9876543214,2024-05-05,48000
6,106,Sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
8,108,Anita Joseph,BENGALURU,FEMALE,919876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000

In [65]:
df1[df1['Customer Name'].str.contains('un',case=False,na=True)]

    Customer ID Customer Name     City  Gender       Phone   Join Date Salary
9           109          None  Chennai  Female  9876543218        None   None
12          103    Arun Kumar  CHENNAI       M  9876543212  2024-03-10  55000

## Datatype Conversion / Type Casting

In [66]:
df1

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,919876543210,2024-01-15,50000
1,102,Priya Sharma,Chennai,female,919876543211,15/02/2024,60000
4,104,Meena Rao,madras,F,919876543213,20/04/2024,70000
5,105,Rahul Das,Salem,MALE,9876543214,2024-05-05,48000
6,106,Sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,Karthik,Bangalore,m,919876543216,2024-07-15,58000
8,108,Anita Joseph,BENGALURU,FEMALE,919876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,None,2024-10-01,72000
12,103,Arun Kumar,CHENNAI,M,9876543212,2024-03-10,55000

In [67]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 12
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    10 non-null     int64
 1   Customer Name  9 non-null      object
 2   City           10 non-null     object
 3   Gender         10 non-null     object
 4   Phone          9 non-null      object
 5   Join Date      9 non-null      object
 6   Salary         9 non-null      object
dtypes: int64(1), object(6)
memory usage: 640.0+ bytes

In [124]:
df1

    Cust_ID     Cust_Name       City  Gender         Phone  Join_Date   Salary
0       101    John Smith    chennai    Male  919876543210 2024-01-15  50000.0
1       102  Priya Sharma    Chennai  Female  919876543211 2024-02-15  60000.0
4       104     Meena Rao     madras  Female  919876543213 2024-04-20  70000.0
5       105     Rahul Das      Salem    Male    9876543214 2024-05-05  48000.0
6       106    Sneha Iyer      SALEM  Female    9876543215 2024-06-06  62000.0
7       107       Karthik  Bangalore    Male  919876543216 2024-07-15  58000.0
8       108  Anita Joseph  BENGALURU  Female  919876543217 2024-08-20  65000.0
9       109          None    Chennai  Female    9876543218        NaT      NaN
10      110   Vijay Kumar    chennai    Male             0 2024-10-01  72000.0
12      103    Arun Kumar    CHENNAI    Male    9876543212 2024-03-10  55000.0

In [70]:
df1['Phone'] = df1['Phone'].astype('int',errors='ignore')

In [72]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 12
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    10 non-null     int64
 1   Customer Name  9 non-null      object
 2   City           10 non-null     object
 3   Gender         10 non-null     object
 4   Phone          9 non-null      object
 5   Join Date      9 non-null      object
 6   Salary         9 non-null      object
dtypes: int64(1), object(6)
memory usage: 640.0+ bytes

In [73]:
df1['Phone'].fillna(0,inplace=True)

/tmp/ipykernel_11730/4144226254.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Phone'].fillna(0,inplace=True)

In [86]:
type(df['Phone'].iloc[8])

NoneType

In [74]:
df1

,Customer ID,Customer Name,City,Gender,Phone,Join Date,Salary
0,101,John Smith,chennai,Male,919876543210,2024-01-15,50000
1,102,Priya Sharma,Chennai,female,919876543211,15/02/2024,60000
4,104,Meena Rao,madras,F,919876543213,20/04/2024,70000
5,105,Rahul Das,Salem,MALE,9876543214,2024-05-05,48000
6,106,Sneha Iyer,SALEM,Female,9876543215,06/06/2024,62000
7,107,Karthik,Bangalore,m,919876543216,2024-07-15,58000
8,108,Anita Joseph,BENGALURU,FEMALE,919876543217,20/08/2024,65000
9,109,None,Chennai,Female,9876543218,None,None
10,110,Vijay Kumar,chennai,Male,0,2024-10-01,72000
12,103,Arun Kumar,CHENNAI,M,9876543212,2024-03-10,55000

In [75]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 12
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    10 non-null     int64
 1   Customer Name  9 non-null      object
 2   City           10 non-null     object
 3   Gender         10 non-null     object
 4   Phone          10 non-null     object
 5   Join Date      9 non-null      object
 6   Salary         9 non-null      object
dtypes: int64(1), object(6)
memory usage: 640.0+ bytes

In [76]:
df1['Phone'] = df1['Phone'].astype('int',errors='ignore')
df1['Phone'].dtype

dtype('int64')

In [77]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 12
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    10 non-null     int64
 1   Customer Name  9 non-null      object
 2   City           10 non-null     object
 3   Gender         10 non-null     object
 4   Phone          10 non-null     int64
 5   Join Date      9 non-null      object
 6   Salary         9 non-null      object
dtypes: int64(2), object(5)
memory usage: 640.0+ bytes

In [78]:
df1['Salary'] = df1['Salary'].astype('float')

In [79]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 12
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    10 non-null     int64
 1   Customer Name  9 non-null      object
 2   City           10 non-null     object
 3   Gender         10 non-null     object
 4   Phone          10 non-null     int64
 5   Join Date      9 non-null      object
 6   Salary         9 non-null      float64
dtypes: float64(1), int64(2), object(4)
memory usage: 640.0+ bytes

## Data Time Conversion

In [87]:
pd.to_datetime("01/05/2024")

Timestamp('2024-01-05 00:00:00')

In [88]:
pd.to_datetime("01/05/2024",dayfirst=True)

Timestamp('2024-05-01 00:00:00')

In [89]:
pd.to_datetime("01-05-2024")

Timestamp('2024-01-05 00:00:00')

In [90]:
pd.to_datetime("02-05-2024",dayfirst=True)

Timestamp('2024-05-02 00:00:00')

In [93]:
df1['Join Date'] = pd.to_datetime(df1['Join Date'],dayfirst=True,format='mixed')

In [94]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 12
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    10 non-null     int64
 1   Customer Name  9 non-null      object
 2   City           10 non-null     object
 3   Gender         10 non-null     object
 4   Phone          10 non-null     int64
 5   Join Date      9 non-null      datetime64[ns]
 6   Salary         9 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 640.0+ bytes

In [125]:
df1['year']=df1['Join_Date'].dt.year
df1

,Cust_ID,Cust_Name,City,Gender,Phone,Join_Date,Salary,year
0,101,John Smith,chennai,Male,919876543210,2024-01-15,50000.0,2024.0
1,102,Priya Sharma,Chennai,Female,919876543211,2024-02-15,60000.0,2024.0
4,104,Meena Rao,madras,Female,919876543213,2024-04-20,70000.0,2024.0
5,105,Rahul Das,Salem,Male,9876543214,2024-05-05,48000.0,2024.0
6,106,Sneha Iyer,SALEM,Female,9876543215,2024-06-06,62000.0,2024.0
7,107,Karthik,Bangalore,Male,919876543216,2024-07-15,58000.0,2024.0
8,108,Anita Joseph,BENGALURU,Female,919876543217,2024-08-20,65000.0,2024.0
9,109,None,Chennai,Female,9876543218,NaT,NaN,NaN
10,110,Vijay Kumar,chennai,Male,0,2024-10-01,72000.0,2024.0
12,103,Arun Kumar,CHENNAI,Male,9876543212,2024-03-10,55000.0,2024.0

In [130]:
df1['Month'] = df1['Join_Date'].dt.month
df1['Day'] = df1['Join_Date'].dt.day
df1['DoW'] = df1['Join_Date'].dt.dayofweek
df1['DoY'] = df1['Join_Date'].dt.dayofyear
df1['Week'] = df1['Join_Date'].dt.isocalendar().week
df1

,Cust_ID,Cust_Name,City,Gender,Phone,Join_Date,Salary,year,Month,Day,DoW,DoY,Week
0,101,John Smith,chennai,Male,919876543210,2024-01-15,50000.0,2024.0,1.0,15.0,0.0,15.0,3
1,102,Priya Sharma,Chennai,Female,919876543211,2024-02-15,60000.0,2024.0,2.0,15.0,3.0,46.0,7
4,104,Meena Rao,madras,Female,919876543213,2024-04-20,70000.0,2024.0,4.0,20.0,5.0,111.0,16
5,105,Rahul Das,Salem,Male,9876543214,2024-05-05,48000.0,2024.0,5.0,5.0,6.0,126.0,18
6,106,Sneha Iyer,SALEM,Female,9876543215,2024-06-06,62000.0,2024.0,6.0,6.0,3.0,158.0,23
7,107,Karthik,Bangalore,Male,919876543216,2024-07-15,58000.0,2024.0,7.0,15.0,0.0,197.0,29
8,108,Anita Joseph,BENGALURU,Female,919876543217,2024-08-20,65000.0,2024.0,8.0,20.0,1.0,233.0,34
9,109,None,Chennai,Female,9876543218,NaT,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
10,110,Vijay Kumar,chennai,Male,0,2024-10-01,72000.0,2024.0,10.0,1.0,1.0,275.0,40
12,103,Arun Kumar,CHENNAI,Male,9876543212,2024-03-10,55000.0,2024.0,3.0,10.0,6.0,70.0,10

## Standard

In [95]:
df1['Gender']

0       Male
1     female
4          F
5       MALE
6     Female
7          m
8     FEMALE
9     Female
10      Male
12         M
Name: Gender, dtype: object

In [97]:
df1['Gender'] = df1['Gender'].str.strip().str.title()
df1['Gender']

0       Male
1     Female
4          F
5       Male
6     Female
7          M
8     Female
9     Female
10      Male
12         M
Name: Gender, dtype: object

In [99]:
df1['Gender'].value_counts()

Gender
Female    4
Male      3
M         2
F         1
Name: count, dtype: int64

In [100]:
df1['Gender'].replace('M','Male',inplace=True)
df1['Gender'].replace('F','Female',inplace=True)

In [101]:
df1['Gender']

0       Male
1     Female
4     Female
5       Male
6     Female
7       Male
8     Female
9     Female
10      Male
12      Male
Name: Gender, dtype: object

## Column Rename

In [102]:
df1.columns

Index(['Customer ID', 'Customer Name', 'City', 'Gender', 'Phone', 'Join Date',
       'Salary'],
      dtype='object')

In [103]:
df1.rename(columns={"Customer ID":"Cust_ID","Customer Name":"Cust_Name","Join Date":"Join_Date"},inplace=True)

In [104]:
df1

    Cust_ID     Cust_Name       City  Gender         Phone  Join_Date   Salary
0       101    John Smith    chennai    Male  919876543210 2024-01-15  50000.0
1       102  Priya Sharma    Chennai  Female  919876543211 2024-02-15  60000.0
4       104     Meena Rao     madras  Female  919876543213 2024-04-20  70000.0
5       105     Rahul Das      Salem    Male    9876543214 2024-05-05  48000.0
6       106    Sneha Iyer      SALEM  Female    9876543215 2024-06-06  62000.0
7       107       Karthik  Bangalore    Male  919876543216 2024-07-15  58000.0
8       108  Anita Joseph  BENGALURU  Female  919876543217 2024-08-20  65000.0
9       109          None    Chennai  Female    9876543218        NaT      NaN
10      110   Vijay Kumar    chennai    Male             0 2024-10-01  72000.0
12      103    Arun Kumar    CHENNAI    Male    9876543212 2024-03-10  55000.0

In [105]:
df1['Phone']

0     919876543210
1     919876543211
4     919876543213
5       9876543214
6       9876543215
7     919876543216
8     919876543217
9       9876543218
10               0
12      9876543212
Name: Phone, dtype: int64

## Regex - Regular Expression

In [108]:
df['Phone'].dtype

dtype('O')

In [110]:
df['New_phone'] = df['Phone'].str.extract(r'(\d{10})')
df[['Phone','New_phone']]

/tmp/ipykernel_11730/2904403774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['New_phone'] = df['Phone'].str.extract(r'(\d{10})')

           Phone   New_phone
0   919876543210  9198765432
1   919876543211  9198765432
4   919876543213  9198765432
5     9876543214  9876543214
6     9876543215  9876543215
7   919876543216  9198765432
8   919876543217  9198765432
9     9876543218  9876543218
10          None         NaN
12    9876543212  9876543212

In [111]:
df['New_phone2'] = df['Phone'].str.extract(r'(\d{10})$')
df[['Phone','New_phone','New_phone2']]

/tmp/ipykernel_11730/747700905.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['New_phone2'] = df['Phone'].str.extract(r'(\d{10})$')

           Phone   New_phone  New_phone2
0   919876543210  9198765432  9876543210
1   919876543211  9198765432  9876543211
4   919876543213  9198765432  9876543213
5     9876543214  9876543214  9876543214
6     9876543215  9876543215  9876543215
7   919876543216  9198765432  9876543216
8   919876543217  9198765432  9876543217
9     9876543218  9876543218  9876543218
10          None         NaN         NaN
12    9876543212  9876543212  9876543212

### Simple Regex Symbols

- `\d` → a digit
- `+` → one or more
- `{10}` → exactly 10 occurrences
- `()` → capture the matching part
- `$`→ End of the string

In [112]:
data = {'Ord':["ORD-10","ORD-11","ORD-101","ORD-1001"],
        'Name':["Selva","Vinoth","Arun","Shiva"]}
df3 = pd.DataFrame(data)
df3

        Ord    Name
0    ORD-10   Selva
1    ORD-11  Vinoth
2   ORD-101    Arun
3  ORD-1001   Shiva

In [114]:
df3['Ord'].str.extract(r'(\d+)')

      0
0    10
1    11
2   101
3  1001

In [121]:
df1['Phone'].dtype

dtype('int64')

## Custom function for dataframe

In [119]:
def div(num):
  num = num%10000000000
  return num

In [122]:
df1['Phone'].apply(div)

0     9876543210
1     9876543211
4     9876543213
5     9876543214
6     9876543215
7     9876543216
8     9876543217
9     9876543218
10             0
12    9876543212
Name: Phone, dtype: int64

In [131]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 12
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Cust_ID    10 non-null     int64
 1   Cust_Name  9 non-null      object
 2   City       10 non-null     object
 3   Gender     10 non-null     object
 4   Phone      10 non-null     int64
 5   Join_Date  9 non-null      datetime64[ns]
 6   Salary     9 non-null      float64
 7   year       9 non-null      float64
 8   Month      9 non-null      float64
 9   Day        9 non-null      float64
 10  DoW        9 non-null      float64
 11  DoY        9 non-null      float64
 12  Week       9 non-null      UInt32
dtypes: UInt32(1), datetime64[ns](1), float64(6), int64(2), object(3)
memory usage: 1.1+ KB

## View Selective datatype columns in DF

In [134]:
df1.select_dtypes(include='number')

    Cust_ID         Phone   Salary    year  Month   Day  DoW    DoY  Week
0       101  919876543210  50000.0  2024.0    1.0  15.0  0.0   15.0     3
1       102  919876543211  60000.0  2024.0    2.0  15.0  3.0   46.0     7
4       104  919876543213  70000.0  2024.0    4.0  20.0  5.0  111.0    16
5       105    9876543214  48000.0  2024.0    5.0   5.0  6.0  126.0    18
6       106    9876543215  62000.0  2024.0    6.0   6.0  3.0  158.0    23
7       107  919876543216  58000.0  2024.0    7.0  15.0  0.0  197.0    29
8       108  919876543217  65000.0  2024.0    8.0  20.0  1.0  233.0    34
9       109    9876543218      NaN     NaN    NaN   NaN  NaN    NaN  <NA>
10      110             0  72000.0  2024.0   10.0   1.0  1.0  275.0    40
12      103    9876543212  55000.0  2024.0    3.0  10.0  6.0   70.0    10

In [135]:
df1.select_dtypes(include='object')

       Cust_Name       City  Gender
0     John Smith    chennai    Male
1   Priya Sharma    Chennai  Female
4      Meena Rao     madras  Female
5      Rahul Das      Salem    Male
6     Sneha Iyer      SALEM  Female
7        Karthik  Bangalore    Male
8   Anita Joseph  BENGALURU  Female
9           None    Chennai  Female
10   Vijay Kumar    chennai    Male
12    Arun Kumar    CHENNAI    Male

In [136]:
df1.select_dtypes(include='datetime')

    Join_Date
0  2024-01-15
1  2024-02-15
4  2024-04-20
5  2024-05-05
6  2024-06-06
7  2024-07-15
8  2024-08-20
9         NaT
10 2024-10-01
12 2024-03-10