In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Loan_Dataset.csv")
df

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,dtir1,Status
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758.0,CIB,25-34,to_inst,98.728814,south,direct,45.000000,1.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552.0,EXP,55-64,to_inst,72.746457,North,direct,37.732932,1.0
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834.0,CIB,35-44,to_inst,80.019685,south,direct,46.000000,0.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587.0,CIB,45-54,not_inst,69.376900,North,direct,42.000000,0.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602.0,EXP,25-34,not_inst,91.886544,North,direct,39.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123356,148246,2019,cf,Sex Not Available,nopre,type3,p3,l1,nopc,nob/c,...,CIB,713.0,EXP,65-74,to_inst,122.265625,south,direct,37.000000,1.0
123357,148247,2019,ncf,Joint,nopre,type1,p4,l1,nopc,nob/c,...,CRIF,818.0,EXP,35-44,not_inst,56.457314,south,direct,32.000000,0.0
123358,148248,2019,cf,Sex Not Available,nopre,type3,p1,l1,nopc,nob/c,...,EQUI,701.0,EXP,25-34,not_inst,72.746457,south,direct,37.732932,1.0
123359,148249,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,...,EXP,776.0,CIB,45-54,to_inst,51.344086,south,direct,37.000000,1.0
123360,148250,2019,cf,Male,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(148670, 34)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148670 entries, 0 to 148669
Data columns (total 34 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ID                         148670 non-null  int64
 1   year                       148670 non-null  int64
 2   loan_limit                 148670 non-null  object
 3   Gender                     148670 non-null  object
 4   approv_in_adv              148670 non-null  object
 5   loan_type                  148670 non-null  object
 6   loan_purpose               148670 non-null  object
 7   Credit_Worthiness          148670 non-null  object
 8   open_credit                148670 non-null  object
 9   business_or_commercial     148670 non-null  object
 10  loan_amount                148670 non-null  int64
 11  rate_of_interest           148670 non-null  float64
 12  Interest_rate_spread       148670 non-null  float64
 13  Upfront_charges            148670 non-null  float64
 14  term                       148670 non-null  float64
 15  Neg_ammortization          148670 non-null  object
 16  interest_only              148670 non-null  object
 17  lump_sum_payment           148670 non-null  object
 18  property_value             148670 non-null  float64
 19  construction_type          148670 non-null  object
 20  occupancy_type             148670 non-null  object
 21  Secured_by                 148670 non-null  object
 22  total_units                148670 non-null  object
 23  income                     148670 non-null  float64
 24  credit_type                148670 non-null  object
 25  Credit_Score               148670 non-null  int64
 26  co-applicant_credit_type   148670 non-null  object
 27  age                        148670 non-null  object
 28  submission_of_application  148670 non-null  object
 29  LTV                        148670 non-null  float64
 30  Region                     148670 non-null  object
 31  Security_Type              148670 non-null  object
 32  dtir1                      148670 non-null  float64
 33  Status                     148670 non-null  int64
dtypes: float64(8), int64(5), object(21)
memory usage: 38.6+ MB

In [ ]:
cat_column = df.select_dtypes(include='object').columns.tolist()
cat_column

['loan_limit',
 'Gender',
 'approv_in_adv',
 'loan_type',
 'loan_purpose',
 'Credit_Worthiness',
 'open_credit',
 'business_or_commercial',
 'Neg_ammortization',
 'interest_only',
 'lump_sum_payment',
 'construction_type',
 'occupancy_type',
 'Secured_by',
 'total_units',
 'credit_type',
 'co-applicant_credit_type',
 'age',
 'submission_of_application',
 'Region',
 'Security_Type']

In [ ]:
df['loan_limit'].nunique()

2

In [ ]:
df['loan_limit'].value_counts()

loan_limit
cf     138692
ncf      9978
Name: count, dtype: int64

In [ ]:
for i in cat_column:
    print(i, ": ",df[i].nunique())
    print(df[i].value_counts(),"\n")
    print("*"*50,"\n")

loan_limit :  2
loan_limit
cf     138692
ncf      9978
Name: count, dtype: int64

**************************************************

Gender :  4
Gender
Male                 42346
Joint                41399
Sex Not Available    37659
Female               27266
Name: count, dtype: int64

**************************************************

approv_in_adv :  2
approv_in_adv
nopre    125529
pre       23141
Name: count, dtype: int64

**************************************************

loan_type :  3
loan_type
type1    113173
type2     20762
type3     14735
Name: count, dtype: int64

**************************************************

loan_purpose :  4
loan_purpose
p3    56068
p4    54799
p1    34529
p2     3274
Name: count, dtype: int64

**************************************************

Credit_Worthiness :  2
Credit_Worthiness
l1    142344
l2      6326
Name: count, dtype: int64

**************************************************

open_credit :  2
open_credit
nopc    148114
opc        556
Name: count, dtype: int64

**************************************************

business_or_commercial :  2
business_or_commercial
nob/c    127908
b/c       20762
Name: count, dtype: int64

**************************************************

Neg_ammortization :  2
Neg_ammortization
not_neg    133541
neg_amm     15129
Name: count, dtype: int64

**************************************************

interest_only :  2
interest_only
not_int     141560
int_only      7110
Name: count, dtype: int64

**************************************************

lump_sum_payment :  2
lump_sum_payment
not_lpsm    145286
lpsm          3384
Name: count, dtype: int64

**************************************************

construction_type :  2
construction_type
sb    148637
mh        33
Name: count, dtype: int64

**************************************************

occupancy_type :  3
occupancy_type
pr    138201
ir      7340
sr      3129
Name: count, dtype: int64

**************************************************

Secured_by :  2
Secured_by
home    148637
land        33
Name: count, dtype: int64

**************************************************

total_units :  4
total_units
1U    146480
2U      1477
3U       393
4U       320
Name: count, dtype: int64

**************************************************

credit_type :  4
credit_type
CIB     48152
CRIF    43901
EXP     41319
EQUI    15298
Name: count, dtype: int64

**************************************************

co-applicant_credit_type :  2
co-applicant_credit_type
CIB    74392
EXP    74278
Name: count, dtype: int64

**************************************************

age :  7
age
45-54    34920
35-44    32818
55-64    32534
65-74    20744
25-34    19142
>74       7175
<25       1337
Name: count, dtype: int64

**************************************************

submission_of_application :  2
submission_of_application
to_inst     96014
not_inst    52656
Name: count, dtype: int64

**************************************************

Region :  4
Region
North         74722
south         64016
central        8697
North-East     1235
Name: count, dtype: int64

**************************************************

Security_Type :  2
Security_Type
direct      148637
Indriect        33
Name: count, dtype: int64

**************************************************

# Encoding

## Binary Category

In [ ]:
df['loan_limit_enc'] = df['loan_limit'].map({'cf':0,'ncf':1})

In [ ]:
df['loan_limit'].value_counts()

loan_limit
cf     138692
ncf      9978
Name: count, dtype: int64

In [ ]:
df['approv_in_adv_enc'] = df['approv_in_adv'].replace({'nopre':0,'pre':1})

/tmp/ipykernel_3826/3153747504.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['approv_in_adv_enc'] = df['approv_in_adv'].replace({'nopre':0,'pre':1})

In [ ]:
df[['approv_in_adv_enc','approv_in_adv']]

        approv_in_adv_enc approv_in_adv
0                       0         nopre
1                       0         nopre
2                       1           pre
3                       0         nopre
4                       1           pre
...                   ...           ...
148665                  0         nopre
148666                  0         nopre
148667                  0         nopre
148668                  0         nopre
148669                  0         nopre

[148670 rows x 2 columns]

## Ordinal

### Ordinal Encoder

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df['age'].unique().tolist()

['25-34', '55-64', '35-44', '45-54', '65-74', '>74', '<25']

In [ ]:
ord_encoder = OrdinalEncoder(categories=[['<25','25-34','35-44', '45-54','55-64', '65-74', '>74']])
df['age_enc'] = ord_encoder.fit_transform(df[['age']])

In [ ]:
df[['age','age_enc']].head(50)

      age  age_enc
0   25-34      1.0
1   55-64      4.0
2   35-44      2.0
3   45-54      3.0
4   25-34      1.0
5   35-44      2.0
6   55-64      4.0
7   55-64      4.0
8   55-64      4.0
9   55-64      4.0
10  55-64      4.0
11  35-44      2.0
12  65-74      5.0
13  55-64      4.0
14  35-44      2.0
15  45-54      3.0
16  25-34      1.0
17  65-74      5.0
18  45-54      3.0
19  55-64      4.0
20  65-74      5.0
21    >74      6.0
22  55-64      4.0
23  65-74      5.0
24  35-44      2.0
25  45-54      3.0
26  45-54      3.0
27  25-34      1.0
28  55-64      4.0
29  35-44      2.0
30  25-34      1.0
31  55-64      4.0
32  35-44      2.0
33  45-54      3.0
34  25-34      1.0
35  45-54      3.0
36  55-64      4.0
37  45-54      3.0
38  65-74      5.0
39  35-44      2.0
40  35-44      2.0
41  35-44      2.0
42  45-54      3.0
43  35-44      2.0
44  35-44      2.0
45  45-54      3.0
46  55-64      4.0
47  55-64      4.0
48  45-54      3.0
49  25-34      1.0

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb_encoder = LabelEncoder()
df['age_enc_lb'] = lb_encoder.fit_transform(df['age'])

In [ ]:
df[['age','age_enc','age_enc_lb']]

          age  age_enc  age_enc_lb
0       25-34      1.0           0
1       55-64      4.0           3
2       35-44      2.0           1
3       45-54      3.0           2
4       25-34      1.0           0
...       ...      ...         ...
148665  55-64      4.0           3
148666  25-34      1.0           0
148667  45-54      3.0           2
148668  55-64      4.0           3
148669  45-54      3.0           2

[148670 rows x 3 columns]

| **Aspect**                    | **OrdinalEncoder**                                    | **LabelEncoder**                                                                  |
| ----------------------------- | ----------------------------------------------------- | --------------------------------------------------------------------------------- |
| **Purpose**                   | Encodes **categorical features/columns** into numbers | Encodes **target labels/classes** into numbers                                    |
| **Main use**                  | For **input features (X)**                            | Mainly for **target variable (y)**                                                |
| **Works on**                  | One or multiple feature columns                       | Typically one target column                                                       |
| **Output**                    | 2D array                                              | 1D array                                                                          |
| **Ordering**                  | Can explicitly define meaningful category order       | Assigns numbers based on sorted class labels; order is not necessarily meaningful |
| **Example**                   | `Low → 0, Medium → 1, High → 2`                       | `No → 0, Yes → 1`                                                                 |
| **Best suited for**           | **Ordinal categorical features**                      | **Categorical target variable**                                                   |
| **Can specify custom order?** | ✅ Yes, using `categories=`                            | ❌ No custom ordinal meaning                                                       |
| **Multiple columns?**         | ✅ Yes                                                 | ❌ Designed for a single target array                                              |
| **Typical ML usage**          | `X` preprocessing                                     | `y` preprocessing                                                                 |
| **Scikit-learn module**       | `sklearn.preprocessing.OrdinalEncoder`                | `sklearn.preprocessing.LabelEncoder`                                              |

## Nominal Encoding

In [ ]:
df.head(10)

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,dtir1,Status
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758.0,CIB,25-34,to_inst,98.728814,south,direct,45.000000,1.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552.0,EXP,55-64,to_inst,72.746457,North,direct,37.732932,1.0
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834.0,CIB,35-44,to_inst,80.019685,south,direct,46.000000,0.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587.0,CIB,45-54,not_inst,69.376900,North,direct,42.000000,0.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602.0,EXP,25-34,not_inst,91.886544,North,direct,39.000000,0.0
5,24895,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,EXP,864.0,EXP,35-44,not_inst,70.089286,North,direct,40.000000,0.0
6,24896,2019,cf,Joint,pre,type1,p3,l1,nopc,nob/c,...,EXP,860.0,EXP,55-64,to_inst,79.109589,North,direct,44.000000,0.0
7,24897,2019,cf,Female,nopre,type1,p4,l1,nopc,nob/c,...,CIB,863.0,CIB,55-64,to_inst,86.525974,North,direct,42.000000,0.0
8,24898,2019,cf,Joint,nopre,type1,p3,l1,nopc,nob/c,...,CIB,580.0,EXP,55-64,to_inst,78.765690,central,direct,44.000000,0.0
9,24899,2019,cf,Sex Not Available,nopre,type3,p3,l1,nopc,nob/c,...,CIB,788.0,EXP,55-64,to_inst,63.444767,south,direct,30.000000,0.0

### One Hot Encoding

#### pd.get_dummies()

In [ ]:
df['credit_type'].value_counts()

credit_type
CIB     39987
CRIF    36389
EXP     34331
EQUI    12653
Name: count, dtype: int64

In [ ]:
df_1 = pd.get_dummies(df,columns=['credit_type'],dtype=int,drop_first=True)

In [ ]:
df_1

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,age,submission_of_application,LTV,Region,Security_Type,dtir1,Status,credit_type_CRIF,credit_type_EQUI,credit_type_EXP
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,25-34,to_inst,98.728814,south,direct,45.000000,1.0,0,0,1
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,55-64,to_inst,72.746457,North,direct,37.732932,1.0,0,1,0
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,35-44,to_inst,80.019685,south,direct,46.000000,0.0,0,0,1
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,45-54,not_inst,69.376900,North,direct,42.000000,0.0,0,0,1
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,25-34,not_inst,91.886544,North,direct,39.000000,0.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123356,148246,2019,cf,Sex Not Available,nopre,type3,p3,l1,nopc,nob/c,...,65-74,to_inst,122.265625,south,direct,37.000000,1.0,0,0,0
123357,148247,2019,ncf,Joint,nopre,type1,p4,l1,nopc,nob/c,...,35-44,not_inst,56.457314,south,direct,32.000000,0.0,1,0,0
123358,148248,2019,cf,Sex Not Available,nopre,type3,p1,l1,nopc,nob/c,...,25-34,not_inst,72.746457,south,direct,37.732932,1.0,0,1,0
123359,148249,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,...,45-54,to_inst,51.344086,south,direct,37.000000,1.0,0,0,1
123360,148250,2019,cf,Male,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0

In [ ]:
df.columns

Index(['ID', 'year', 'loan_limit', 'Gender', 'approv_in_adv', 'loan_type',
       'loan_purpose', 'Credit_Worthiness', 'open_credit',
       'business_or_commercial', 'loan_amount', 'rate_of_interest',
       'Interest_rate_spread', 'Upfront_charges', 'term', 'Neg_ammortization',
       'interest_only', 'lump_sum_payment', 'property_value',
       'construction_type', 'occupancy_type', 'Secured_by', 'total_units',
       'income', 'credit_type', 'Credit_Score', 'co-applicant_credit_type',
       'age', 'submission_of_application', 'LTV', 'Region', 'Security_Type',
       'dtir1', 'Status'],
      dtype='object')

In [ ]:
df_1.columns

Index(['ID', 'year', 'loan_limit', 'Gender', 'approv_in_adv', 'loan_type',
       'loan_purpose', 'Credit_Worthiness', 'open_credit',
       'business_or_commercial', 'loan_amount', 'rate_of_interest',
       'Interest_rate_spread', 'Upfront_charges', 'term', 'Neg_ammortization',
       'interest_only', 'lump_sum_payment', 'property_value',
       'construction_type', 'occupancy_type', 'Secured_by', 'total_units',
       'income', 'Credit_Score', 'co-applicant_credit_type', 'age',
       'submission_of_application', 'LTV', 'Region', 'Security_Type', 'dtir1',
       'Status', 'credit_type_CRIF', 'credit_type_EQUI', 'credit_type_EXP'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one_enc = OneHotEncoder(drop='first',handle_unknown='ignore',sparse_output=False)
credit_type_enc = one_enc.fit_transform(df[['credit_type']])

In [ ]:
credit_type_enc

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
credit_type_column_names = one_enc.get_feature_names_out(['credit_type'])

In [ ]:
encode_df = pd.DataFrame(credit_type_enc,columns=credit_type_column_names)
encode_df

        credit_type_CRIF  credit_type_EQUI  credit_type_EXP  credit_type_nan
0                    0.0               0.0              1.0              0.0
1                    0.0               1.0              0.0              0.0
2                    0.0               0.0              1.0              0.0
3                    0.0               0.0              1.0              0.0
4                    1.0               0.0              0.0              0.0
...                  ...               ...              ...              ...
123356               0.0               0.0              0.0              0.0
123357               1.0               0.0              0.0              0.0
123358               0.0               1.0              0.0              0.0
123359               0.0               0.0              1.0              0.0
123360               0.0               0.0              0.0              1.0

[123361 rows x 4 columns]

In [ ]:
encode_df = encode_df.drop('credit_type_nan',axis = 1)
encode_df

        credit_type_CRIF  credit_type_EQUI  credit_type_EXP
0                    0.0               0.0              1.0
1                    0.0               1.0              0.0
2                    0.0               0.0              1.0
3                    0.0               0.0              1.0
4                    1.0               0.0              0.0
...                  ...               ...              ...
123356               0.0               0.0              0.0
123357               1.0               0.0              0.0
123358               0.0               1.0              0.0
123359               0.0               0.0              1.0
123360               0.0               0.0              0.0

[123361 rows x 3 columns]

In [ ]:
df_4 = pd.concat([df,encode_df],axis=1)
df_4

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,age,submission_of_application,LTV,Region,Security_Type,dtir1,Status,credit_type_CRIF,credit_type_EQUI,credit_type_EXP
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,25-34,to_inst,98.728814,south,direct,45.000000,1.0,0.0,0.0,1.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,55-64,to_inst,72.746457,North,direct,37.732932,1.0,0.0,1.0,0.0
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,35-44,to_inst,80.019685,south,direct,46.000000,0.0,0.0,0.0,1.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,45-54,not_inst,69.376900,North,direct,42.000000,0.0,0.0,0.0,1.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,25-34,not_inst,91.886544,North,direct,39.000000,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123356,148246,2019,cf,Sex Not Available,nopre,type3,p3,l1,nopc,nob/c,...,65-74,to_inst,122.265625,south,direct,37.000000,1.0,0.0,0.0,0.0
123357,148247,2019,ncf,Joint,nopre,type1,p4,l1,nopc,nob/c,...,35-44,not_inst,56.457314,south,direct,32.000000,0.0,1.0,0.0,0.0
123358,148248,2019,cf,Sex Not Available,nopre,type3,p1,l1,nopc,nob/c,...,25-34,not_inst,72.746457,south,direct,37.732932,1.0,0.0,1.0,0.0
123359,148249,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,...,45-54,to_inst,51.344086,south,direct,37.000000,1.0,0.0,0.0,1.0
123360,148250,2019,cf,Male,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [ ]:
df_4.columns

Index(['ID', 'year', 'loan_limit', 'Gender', 'approv_in_adv', 'loan_type',
       'loan_purpose', 'Credit_Worthiness', 'open_credit',
       'business_or_commercial', 'loan_amount', 'rate_of_interest',
       'Interest_rate_spread', 'Upfront_charges', 'term', 'Neg_ammortization',
       'interest_only', 'lump_sum_payment', 'property_value',
       'construction_type', 'occupancy_type', 'Secured_by', 'total_units',
       'income', 'credit_type', 'Credit_Score', 'co-applicant_credit_type',
       'age', 'submission_of_application', 'LTV', 'Region', 'Security_Type',
       'dtir1', 'Status', 'credit_type_CRIF', 'credit_type_EQUI',
       'credit_type_EXP'],
      dtype='object')

In [ ]:
df_4 = df_4.drop('credit_type',axis=1)
df_4

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,age,submission_of_application,LTV,Region,Security_Type,dtir1,Status,credit_type_CRIF,credit_type_EQUI,credit_type_EXP
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,25-34,to_inst,98.728814,south,direct,45.000000,1.0,0.0,0.0,1.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,55-64,to_inst,72.746457,North,direct,37.732932,1.0,0.0,1.0,0.0
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,35-44,to_inst,80.019685,south,direct,46.000000,0.0,0.0,0.0,1.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,45-54,not_inst,69.376900,North,direct,42.000000,0.0,0.0,0.0,1.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,25-34,not_inst,91.886544,North,direct,39.000000,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123356,148246,2019,cf,Sex Not Available,nopre,type3,p3,l1,nopc,nob/c,...,65-74,to_inst,122.265625,south,direct,37.000000,1.0,0.0,0.0,0.0
123357,148247,2019,ncf,Joint,nopre,type1,p4,l1,nopc,nob/c,...,35-44,not_inst,56.457314,south,direct,32.000000,0.0,1.0,0.0,0.0
123358,148248,2019,cf,Sex Not Available,nopre,type3,p1,l1,nopc,nob/c,...,25-34,not_inst,72.746457,south,direct,37.732932,1.0,0.0,1.0,0.0
123359,148249,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,...,45-54,to_inst,51.344086,south,direct,37.000000,1.0,0.0,0.0,1.0
123360,148250,2019,cf,Male,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

#### Extra examples

In [ ]:
data = {"standard":["I","II","III","II","II","I","I"],
        'name':['a','b','c','d','e','f','g']}
df_2 = pd.DataFrame(data)
df_2

  standard name
0        I    a
1       II    b
2      III    c
3       II    d
4       II    e
5        I    f
6        I    g

In [ ]:
pd.get_dummies(df_2,columns=['standard'],dtype=int)

  name  standard_I  standard_II  standard_III
0    a           1            0             0
1    b           0            1             0
2    c           0            0             1
3    d           0            1             0
4    e           0            1             0
5    f           1            0             0
6    g           1            0             0

In [ ]:
data = {"standard":["II","III",],
        'name':['i','j']}
df_3 = pd.DataFrame(data)
df_3

  standard name
0       II    i
1      III    j

In [ ]:
pd.get_dummies(df_3,columns=['standard'],dtype=int)

  name  standard_II  standard_III
0    i            1             0
1    j            0             1

In [ ]:
from sklearn.preprocessing import OneHotEncoder

one_enc2 = OneHotEncoder(handle_unknown='ignore',sparse_output=False)

std_enc1 = one_enc2.fit_transform(df_2[['standard']])
std_enc1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [ ]:
std_enc2 = one_enc2.transform(df_3[['standard']])
std_enc2

array([[0., 1., 0.],
       [0., 0., 1.]])

### Binary Encoder

In [ ]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.11.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.13/dist-packages (from category_encoders) (2.1.3)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.13/dist-packages (from category_encoders) (2.2.3)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.5->category_encoders) (2026.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.11.1-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.9/107.9 kB 1.7 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.11.1

In [ ]:
from category_encoders import BinaryEncoder

In [ ]:
df['Region'].unique()

array(['south', 'North', 'central', 'North-East', nan], dtype=object)

In [ ]:
Bi_encoder = BinaryEncoder(cols=['Region'])
df_5 = Bi_encoder.fit_transform(df)
df_5

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,co-applicant_credit_type,age,submission_of_application,LTV,Region_0,Region_1,Region_2,Security_Type,dtir1,Status
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,CIB,25-34,to_inst,98.728814,0,0,1,direct,45.000000,1.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EXP,55-64,to_inst,72.746457,0,1,0,direct,37.732932,1.0
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,CIB,35-44,to_inst,80.019685,0,0,1,direct,46.000000,0.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,CIB,45-54,not_inst,69.376900,0,1,0,direct,42.000000,0.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,EXP,25-34,not_inst,91.886544,0,1,0,direct,39.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123356,148246,2019,cf,Sex Not Available,nopre,type3,p3,l1,nopc,nob/c,...,EXP,65-74,to_inst,122.265625,0,0,1,direct,37.000000,1.0
123357,148247,2019,ncf,Joint,nopre,type1,p4,l1,nopc,nob/c,...,EXP,35-44,not_inst,56.457314,0,0,1,direct,32.000000,0.0
123358,148248,2019,cf,Sex Not Available,nopre,type3,p1,l1,nopc,nob/c,...,EXP,25-34,not_inst,72.746457,0,0,1,direct,37.732932,1.0
123359,148249,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,...,CIB,45-54,to_inst,51.344086,0,0,1,direct,37.000000,1.0
123360,148250,2019,cf,Male,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,0,1,NaN,NaN,NaN

In [ ]:
df['Region'].head(15)

0       south
1       North
2       south
3       North
4       North
5       North
6       North
7       North
8     central
9       south
10      North
11      south
12      North
13      North
14      North
Name: Region, dtype: object

In [ ]:
df_5[['Region_0','Region_1','Region_2']].head(15)

    Region_0  Region_1  Region_2
0          0         0         1
1          0         1         0
2          0         0         1
3          0         1         0
4          0         1         0
5          0         1         0
6          0         1         0
7          0         1         0
8          0         1         1
9          0         0         1
10         0         1         0
11         0         0         1
12         0         1         0
13         0         1         0
14         0         1         0

### Frequency Encoder

In [ ]:
df.head(10)

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,dtir1,Status
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758.0,CIB,25-34,to_inst,98.728814,south,direct,45.000000,1.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552.0,EXP,55-64,to_inst,72.746457,North,direct,37.732932,1.0
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834.0,CIB,35-44,to_inst,80.019685,south,direct,46.000000,0.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587.0,CIB,45-54,not_inst,69.376900,North,direct,42.000000,0.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602.0,EXP,25-34,not_inst,91.886544,North,direct,39.000000,0.0
5,24895,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,EXP,864.0,EXP,35-44,not_inst,70.089286,North,direct,40.000000,0.0
6,24896,2019,cf,Joint,pre,type1,p3,l1,nopc,nob/c,...,EXP,860.0,EXP,55-64,to_inst,79.109589,North,direct,44.000000,0.0
7,24897,2019,cf,Female,nopre,type1,p4,l1,nopc,nob/c,...,CIB,863.0,CIB,55-64,to_inst,86.525974,North,direct,42.000000,0.0
8,24898,2019,cf,Joint,nopre,type1,p3,l1,nopc,nob/c,...,CIB,580.0,EXP,55-64,to_inst,78.765690,central,direct,44.000000,0.0
9,24899,2019,cf,Sex Not Available,nopre,type3,p3,l1,nopc,nob/c,...,CIB,788.0,EXP,55-64,to_inst,63.444767,south,direct,30.000000,0.0

In [ ]:
df['loan_type'].value_counts()

loan_type
type1    93886
type2    17234
type3    12240
Name: count, dtype: int64

In [ ]:
freq_map_loan_type = df['loan_type'].value_counts(normalize=True)
freq_map_loan_type

loan_type
type1    0.761073
type2    0.139705
type3    0.099222
Name: proportion, dtype: float64

In [ ]:
df['loan_type_frq'] = df['loan_type'].map(freq_map_loan_type)
df['loan_type_frq']

0         0.761073
1         0.139705
2         0.761073
3         0.761073
4         0.761073
            ...
123356    0.099222
123357    0.761073
123358    0.099222
123359    0.761073
123360         NaN
Name: loan_type_frq, Length: 123361, dtype: float64

In [ ]:
df[['loan_type','loan_type_frq']]

       loan_type  loan_type_frq
0          type1       0.761073
1          type2       0.139705
2          type1       0.761073
3          type1       0.761073
4          type1       0.761073
...          ...            ...
123356     type3       0.099222
123357     type1       0.761073
123358     type3       0.099222
123359     type1       0.761073
123360       NaN            NaN

[123361 rows x 2 columns]

In [ ]:
!pip install feature_engine

Collecting feature_engine
  Downloading feature_engine-1.9.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.18.2 in /usr/local/lib/python3.13/dist-packages (from feature_engine) (2.1.3)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from feature_engine) (2.2.3)
Requirement already satisfied: scikit-learn>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from feature_engine) (1.6.1)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from feature_engine) (1.16.3)
Requirement already satisfied: statsmodels>=0.11.1 in /usr/local/lib/python3.13/dist-packages (from feature_engine) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2.0->feature_engine) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2.0->feature_engine) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2.0->feature_engine) (2026.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.4.0->feature_engine) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.4.0->feature_engine) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.11.1->feature_engine) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.11.1->feature_engine) (26.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->feature_engine) (1.17.0)
Downloading feature_engine-1.9.4-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.5/243.5 kB 5.2 MB/s eta 0:00:00
Installing collected packages: feature_engine
Successfully installed feature_engine-1.9.4

In [ ]:
from feature_engine.encoding import CountFrequencyEncoder

In [ ]:
cfe = CountFrequencyEncoder(variables=['loan_type'],encoding_method='frequency',missing_values='ignore')
df_6 = cfe.fit_transform(df)
df_6

/usr/local/lib/python3.13/dist-packages/feature_engine/encoding/base_encoder.py:260: UserWarning: During the encoding, NaN values were introduced in the feature(s) loan_type.
  warnings.warn(

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,dtir1,Status,loan_type_frq
0,24890,2019,cf,Sex Not Available,nopre,0.761073,p1,l1,nopc,nob/c,...,758.0,CIB,25-34,to_inst,98.728814,south,direct,45.000000,1.0,0.761073
1,24891,2019,cf,Male,nopre,0.139705,p1,l1,nopc,b/c,...,552.0,EXP,55-64,to_inst,72.746457,North,direct,37.732932,1.0,0.139705
2,24892,2019,cf,Male,pre,0.761073,p1,l1,nopc,nob/c,...,834.0,CIB,35-44,to_inst,80.019685,south,direct,46.000000,0.0,0.761073
3,24893,2019,cf,Male,nopre,0.761073,p4,l1,nopc,nob/c,...,587.0,CIB,45-54,not_inst,69.376900,North,direct,42.000000,0.0,0.761073
4,24894,2019,cf,Joint,pre,0.761073,p1,l1,nopc,nob/c,...,602.0,EXP,25-34,not_inst,91.886544,North,direct,39.000000,0.0,0.761073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123356,148246,2019,cf,Sex Not Available,nopre,0.099222,p3,l1,nopc,nob/c,...,713.0,EXP,65-74,to_inst,122.265625,south,direct,37.000000,1.0,0.099222
123357,148247,2019,ncf,Joint,nopre,0.761073,p4,l1,nopc,nob/c,...,818.0,EXP,35-44,not_inst,56.457314,south,direct,32.000000,0.0,0.761073
123358,148248,2019,cf,Sex Not Available,nopre,0.099222,p1,l1,nopc,nob/c,...,701.0,EXP,25-34,not_inst,72.746457,south,direct,37.732932,1.0,0.099222
123359,148249,2019,cf,Female,nopre,0.761073,p3,l1,nopc,nob/c,...,776.0,CIB,45-54,to_inst,51.344086,south,direct,37.000000,1.0,0.761073
123360,148250,2019,cf,Male,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_6['loan_type_frq']

0         0.761073
1         0.139705
2         0.761073
3         0.761073
4         0.761073
            ...
123356    0.099222
123357    0.761073
123358    0.099222
123359    0.761073
123360         NaN
Name: loan_type_frq, Length: 123361, dtype: float64

### Target Encoder

In [ ]:
from category_encoders import TargetEncoder

In [ ]:
tarenc =TargetEncoder(cols=['Gender'])
df_7 = tarenc.fit_transform(df,df['Gender'])
df_7

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,dtir1,Status,loan_type_frq
0,24890,2019,cf,3.0,nopre,type1,p1,l1,nopc,nob/c,...,758.0,CIB,25-34,to_inst,98.728814,south,direct,45.000000,1.0,0.761073
1,24891,2019,cf,2.0,nopre,type2,p1,l1,nopc,b/c,...,552.0,EXP,55-64,to_inst,72.746457,North,direct,37.732932,1.0,0.139705
2,24892,2019,cf,2.0,pre,type1,p1,l1,nopc,nob/c,...,834.0,CIB,35-44,to_inst,80.019685,south,direct,46.000000,0.0,0.761073
3,24893,2019,cf,2.0,nopre,type1,p4,l1,nopc,nob/c,...,587.0,CIB,45-54,not_inst,69.376900,North,direct,42.000000,0.0,0.761073
4,24894,2019,cf,1.0,pre,type1,p1,l1,nopc,nob/c,...,602.0,EXP,25-34,not_inst,91.886544,North,direct,39.000000,0.0,0.761073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123356,148246,2019,cf,3.0,nopre,type3,p3,l1,nopc,nob/c,...,713.0,EXP,65-74,to_inst,122.265625,south,direct,37.000000,1.0,0.099222
123357,148247,2019,ncf,1.0,nopre,type1,p4,l1,nopc,nob/c,...,818.0,EXP,35-44,not_inst,56.457314,south,direct,32.000000,0.0,0.761073
123358,148248,2019,cf,3.0,nopre,type3,p1,l1,nopc,nob/c,...,701.0,EXP,25-34,not_inst,72.746457,south,direct,37.732932,1.0,0.099222
123359,148249,2019,cf,0.0,nopre,type1,p3,l1,nopc,nob/c,...,776.0,CIB,45-54,to_inst,51.344086,south,direct,37.000000,1.0,0.761073
123360,148250,2019,cf,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Final Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv("Loan_Dataset.csv")
cat_column = df.select_dtypes(include='object').columns.tolist()

print("*"*50,)
print("Total Categorical Column: ",len(cat_column),"\n")
print("*"*50,)
print("*"*50,"\n","\n")
for i in cat_column:
    print(i, ": ",df[i].nunique())
    print(df[i].value_counts(),"\n")
    print("*"*50,"\n")

**************************************************
Total Categorical Column:  21

**************************************************
**************************************************


loan_limit :  2
loan_limit
cf     138692
ncf      9978
Name: count, dtype: int64

**************************************************

Gender :  4
Gender
Male                 42346
Joint                41399
Sex Not Available    37659
Female               27266
Name: count, dtype: int64

**************************************************

approv_in_adv :  2
approv_in_adv
nopre    125529
pre       23141
Name: count, dtype: int64

**************************************************

loan_type :  3
loan_type
type1    113173
type2     20762
type3     14735
Name: count, dtype: int64

**************************************************

loan_purpose :  4
loan_purpose
p3    56068
p4    54799
p1    34529
p2     3274
Name: count, dtype: int64

**************************************************

Credit_Worthiness :  2
Credit_Worthiness
l1    142344
l2      6326
Name: count, dtype: int64

**************************************************

open_credit :  2
open_credit
nopc    148114
opc        556
Name: count, dtype: int64

**************************************************

business_or_commercial :  2
business_or_commercial
nob/c    127908
b/c       20762
Name: count, dtype: int64

**************************************************

Neg_ammortization :  2
Neg_ammortization
not_neg    133541
neg_amm     15129
Name: count, dtype: int64

**************************************************

interest_only :  2
interest_only
not_int     141560
int_only      7110
Name: count, dtype: int64

**************************************************

lump_sum_payment :  2
lump_sum_payment
not_lpsm    145286
lpsm          3384
Name: count, dtype: int64

**************************************************

construction_type :  2
construction_type
sb    148637
mh        33
Name: count, dtype: int64

**************************************************

occupancy_type :  3
occupancy_type
pr    138201
ir      7340
sr      3129
Name: count, dtype: int64

**************************************************

Secured_by :  2
Secured_by
home    148637
land        33
Name: count, dtype: int64

**************************************************

total_units :  4
total_units
1U    146480
2U      1477
3U       393
4U       320
Name: count, dtype: int64

**************************************************

credit_type :  4
credit_type
CIB     48152
CRIF    43901
EXP     41319
EQUI    15298
Name: count, dtype: int64

**************************************************

co-applicant_credit_type :  2
co-applicant_credit_type
CIB    74392
EXP    74278
Name: count, dtype: int64

**************************************************

age :  7
age
45-54    34920
35-44    32818
55-64    32534
65-74    20744
25-34    19142
>74       7175
<25       1337
Name: count, dtype: int64

**************************************************

submission_of_application :  2
submission_of_application
to_inst     96014
not_inst    52656
Name: count, dtype: int64

**************************************************

Region :  4
Region
North         74722
south         64016
central        8697
North-East     1235
Name: count, dtype: int64

**************************************************

Security_Type :  2
Security_Type
direct      148637
Indriect        33
Name: count, dtype: int64

**************************************************

## Binary Class - Direct Mapping

In [3]:
df["loan_limit"] = df["loan_limit"].map({
    "cf": 0,
    "ncf": 1
})

df["approv_in_adv"] = df["approv_in_adv"].map({
    "nopre": 0,
    "pre": 1
})

df["Credit_Worthiness"] = df["Credit_Worthiness"].map({
    "l1": 0,
    "l2": 1
})

df["open_credit"] = df["open_credit"].map({
    "nopc": 0,
    "opc": 1
})

df["business_or_commercial"] = df["business_or_commercial"].map({
    "nob/c": 0,
    "b/c": 1
})

df["Neg_ammortization"] = df["Neg_ammortization"].map({
    "not_neg": 0,
    "neg_amm": 1
})

df["interest_only"] = df["interest_only"].map({
    "not_int": 0,
    "int_only": 1
})

df["lump_sum_payment"] = df["lump_sum_payment"].map({
    "not_lpsm": 0,
    "lpsm": 1
})

df["construction_type"] = df["construction_type"].map({
    "sb": 0,
    "mh": 1
})

df["Secured_by"] = df["Secured_by"].map({
    "home": 0,
    "land": 1
})

df["co-applicant_credit_type"] = df["co-applicant_credit_type"].map({
    "CIB": 0,
    "EXP": 1
})

df["submission_of_application"] = df["submission_of_application"].map({
    "to_inst": 0,
    "not_inst": 1
})

df["Security_Type"] = df["Security_Type"].map({
    "direct": 0,
    "Indriect": 1
})

## Ordinal Encoding

In [4]:
cat_column = df.select_dtypes(include='object').columns.tolist()
print("*"*50,)
print("Total Categorical Column: ",len(cat_column),"\n")
print("*"*50,)
print("*"*50,"\n","\n")
for i in cat_column:
    print(i, ": ",df[i].nunique())
    print(df[i].value_counts(),"\n")
    print("*"*50,"\n")

**************************************************
Total Categorical Column:  8

**************************************************
**************************************************


Gender :  4
Gender
Male                 42346
Joint                41399
Sex Not Available    37659
Female               27266
Name: count, dtype: int64

**************************************************

loan_type :  3
loan_type
type1    113173
type2     20762
type3     14735
Name: count, dtype: int64

**************************************************

loan_purpose :  4
loan_purpose
p3    56068
p4    54799
p1    34529
p2     3274
Name: count, dtype: int64

**************************************************

occupancy_type :  3
occupancy_type
pr    138201
ir      7340
sr      3129
Name: count, dtype: int64

**************************************************

total_units :  4
total_units
1U    146480
2U      1477
3U       393
4U       320
Name: count, dtype: int64

**************************************************

credit_type :  4
credit_type
CIB     48152
CRIF    43901
EXP     41319
EQUI    15298
Name: count, dtype: int64

**************************************************

age :  7
age
45-54    34920
35-44    32818
55-64    32534
65-74    20744
25-34    19142
>74       7175
<25       1337
Name: count, dtype: int64

**************************************************

Region :  4
Region
North         74722
south         64016
central        8697
North-East     1235
Name: count, dtype: int64

**************************************************

In [5]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(
    categories=[
        ["<25", "25-34", "35-44", "45-54", "55-64", "65-74", ">74"],
        ["1U", "2U", "3U", "4U"]
    ]
)

df[["age", "total_units"]] = encoder.fit_transform(
    df[["age", "total_units"]]
)

## One Hot Encoding

In [6]:
cat_column = df.select_dtypes(include='object').columns.tolist()
print("*"*50,)
print("Total Categorical Column: ",len(cat_column),"\n")
print("*"*50,)
print("*"*50,"\n","\n")
for i in cat_column:
    print(i, ": ",df[i].nunique())
    print(df[i].value_counts(),"\n")
    print("*"*50,"\n")

**************************************************
Total Categorical Column:  6

**************************************************
**************************************************


Gender :  4
Gender
Male                 42346
Joint                41399
Sex Not Available    37659
Female               27266
Name: count, dtype: int64

**************************************************

loan_type :  3
loan_type
type1    113173
type2     20762
type3     14735
Name: count, dtype: int64

**************************************************

loan_purpose :  4
loan_purpose
p3    56068
p4    54799
p1    34529
p2     3274
Name: count, dtype: int64

**************************************************

occupancy_type :  3
occupancy_type
pr    138201
ir      7340
sr      3129
Name: count, dtype: int64

**************************************************

credit_type :  4
credit_type
CIB     48152
CRIF    43901
EXP     41319
EQUI    15298
Name: count, dtype: int64

**************************************************

Region :  4
Region
North         74722
south         64016
central        8697
North-East     1235
Name: count, dtype: int64

**************************************************

In [7]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    drop="first",
    sparse_output=False,
    handle_unknown="ignore"
)

encoded = encoder.fit_transform(df[cat_column])
encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(cat_column),
    index=df.index
)
df = pd.concat(
    [df.drop(columns=cat_column),encoded_df],
    axis=1
)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148670 entries, 0 to 148669
Data columns (total 44 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ID                         148670 non-null  int64
 1   year                       148670 non-null  int64
 2   loan_limit                 148670 non-null  int64
 3   approv_in_adv              148670 non-null  int64
 4   Credit_Worthiness          148670 non-null  int64
 5   open_credit                148670 non-null  int64
 6   business_or_commercial     148670 non-null  int64
 7   loan_amount                148670 non-null  int64
 8   rate_of_interest           148670 non-null  float64
 9   Interest_rate_spread       148670 non-null  float64
 10  Upfront_charges            148670 non-null  float64
 11  term                       148670 non-null  float64
 12  Neg_ammortization          148670 non-null  int64
 13  interest_only              148670 non-null  int64
 14  lump_sum_payment           148670 non-null  int64
 15  property_value             148670 non-null  float64
 16  construction_type          148670 non-null  int64
 17  Secured_by                 148670 non-null  int64
 18  total_units                148670 non-null  float64
 19  income                     148670 non-null  float64
 20  Credit_Score               148670 non-null  int64
 21  co-applicant_credit_type   148670 non-null  int64
 22  age                        148670 non-null  float64
 23  submission_of_application  148670 non-null  int64
 24  LTV                        148670 non-null  float64
 25  Security_Type              148670 non-null  int64
 26  dtir1                      148670 non-null  float64
 27  Status                     148670 non-null  int64
 28  Gender_Joint               148670 non-null  float64
 29  Gender_Male                148670 non-null  float64
 30  Gender_Sex Not Available   148670 non-null  float64
 31  loan_type_type2            148670 non-null  float64
 32  loan_type_type3            148670 non-null  float64
 33  loan_purpose_p2            148670 non-null  float64
 34  loan_purpose_p3            148670 non-null  float64
 35  loan_purpose_p4            148670 non-null  float64
 36  occupancy_type_pr          148670 non-null  float64
 37  occupancy_type_sr          148670 non-null  float64
 38  credit_type_CRIF           148670 non-null  float64
 39  credit_type_EQUI           148670 non-null  float64
 40  credit_type_EXP            148670 non-null  float64
 41  Region_North-East          148670 non-null  float64
 42  Region_central             148670 non-null  float64
 43  Region_south               148670 non-null  float64
dtypes: float64(26), int64(18)
memory usage: 49.9 MB

In [10]:
df.to_csv("Loan_Dataset_Encoded.csv",index=False)