In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv("/content/Loan_Dataset_Encoded.csv")

In [4]:
df.head()

,ID,year,loan_limit,approv_in_adv,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,Secured_by,total_units,income,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Security_Type,dtir1,Status,Gender_Joint,Gender_Male,Gender_Sex Not Available,loan_type_type2,loan_type_type3,loan_purpose_p2,loan_purpose_p3,loan_purpose_p4,occupancy_type_pr,occupancy_type_sr,credit_type_CRIF,credit_type_EQUI,credit_type_EXP,Region_North-East,Region_central,Region_south
0,24890,2019,0,0,0,0,0,116500,4.045476,0.441656,3224.996127,360.0,0,0,0,118000.000000,0,0,0.0,1740.0,758,0,1.0,0,98.728814,0,45.000000,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,24891,2019,0,0,0,0,1,206500,4.045476,0.441656,3224.996127,360.0,0,0,1,497893.465696,0,0,0.0,4980.0,552,1,4.0,0,72.746457,0,37.732932,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,24892,2019,0,1,0,0,0,406500,4.560000,0.200000,595.000000,360.0,1,0,0,508000.000000,0,0,0.0,9480.0,834,0,2.0,0,80.019685,0,46.000000,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,24893,2019,0,0,0,0,0,456500,4.250000,0.681000,3224.996127,360.0,0,0,0,658000.000000,0,0,0.0,11880.0,587,0,3.0,1,69.376900,0,42.000000,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,24894,2019,0,1,0,0,0,696500,4.000000,0.304200,0.000000,360.0,0,0,0,758000.000000,0,0,0.0,10440.0,602,1,1.0,1,91.886544,0,39.000000,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

## Standard Scaler

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
s_scaler = StandardScaler()

In [7]:
df['loan_amount_scaled'] = s_scaler.fit_transform(df[['loan_amount']])
df['loan_amount_scaled'].head()

0   -1.166980
1   -0.677607
2    0.409890
3    0.681764
4    1.986759
Name: loan_amount_scaled, dtype: float64

In [8]:
df[['loan_amount','loan_amount_scaled']].head()

   loan_amount  loan_amount_scaled
0       116500           -1.166980
1       206500           -0.677607
2       406500            0.409890
3       456500            0.681764
4       696500            1.986759

In [9]:
df['Upfront_charges_scaled'] = s_scaler.fit_transform(df[['Upfront_charges']])
df['Upfront_charges_scaled'].head()

0   -1.633359e-16
1   -1.633359e-16
2   -9.446405e-01
3   -1.633359e-16
4   -1.158352e+00
Name: Upfront_charges_scaled, dtype: float64

In [10]:
df[['Upfront_charges','Upfront_charges_scaled']]

        Upfront_charges  Upfront_charges_scaled
0           3224.996127           -1.633359e-16
1           3224.996127           -1.633359e-16
2            595.000000           -9.446405e-01
3           3224.996127           -1.633359e-16
4              0.000000           -1.158352e+00
...                 ...                     ...
148665      9960.000000            2.419075e+00
148666         0.000000           -1.158352e+00
148667      1226.640000           -7.177684e-01
148668      4323.330000            3.944989e-01
148669      6000.000000            9.967243e-01

[148670 rows x 2 columns]

## Min Max Scaler

In [11]:
from sklearn.preprocessing import MinMaxScaler
m_scaler = MinMaxScaler()
df['loan_amount_Mscale'] = m_scaler.fit_transform(df[['loan_amount']])

In [12]:
df[['loan_amount','loan_amount_scaled','loan_amount_Mscale']].head()

   loan_amount  loan_amount_scaled  loan_amount_Mscale
0       116500           -1.166980            0.028090
1       206500           -0.677607            0.053371
2       406500            0.409890            0.109551
3       456500            0.681764            0.123596
4       696500            1.986759            0.191011

## Robust Scaler

In [13]:
from sklearn.preprocessing import RobustScaler
r_scaler = RobustScaler()
df['loan_amount_Rscale'] = r_scaler.fit_transform(df[['loan_amount']])

In [14]:
df[['loan_amount','loan_amount_scaled','loan_amount_Mscale','loan_amount_Rscale']].head()

   loan_amount  loan_amount_scaled  loan_amount_Mscale  loan_amount_Rscale
0       116500           -1.166980            0.028090           -0.750000
1       206500           -0.677607            0.053371           -0.375000
2       406500            0.409890            0.109551            0.458333
3       456500            0.681764            0.123596            0.666667
4       696500            1.986759            0.191011            1.666667

| **Technique** | **Main Idea** | **Range** | **Outlier Sensitivity** | **Typical Use** |
|---|---|---|---|---|
| **StandardScaler** | Mean = 0, SD = 1 | No fixed range | High | General-purpose scaling |
| **MinMaxScaler** | Uses minimum and maximum | Usually 0 to 1 | High | Distance-based algorithms |
| **RobustScaler** | Uses median and IQR | No fixed range | **Low** | Data with outliers |

# Final

In [15]:
df = pd.read_csv("/content/Loan_Dataset_Encoded.csv")

In [16]:
df = df.drop(['ID','year'],axis=1)
df

,loan_limit,approv_in_adv,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,Secured_by,total_units,income,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Security_Type,dtir1,Status,Gender_Joint,Gender_Male,Gender_Sex Not Available,loan_type_type2,loan_type_type3,loan_purpose_p2,loan_purpose_p3,loan_purpose_p4,occupancy_type_pr,occupancy_type_sr,credit_type_CRIF,credit_type_EQUI,credit_type_EXP,Region_North-East,Region_central,Region_south
0,0,0,0,0,0,116500,4.045476,0.441656,3224.996127,360.0,0,0,0,118000.000000,0,0,0.0,1740.0,758,0,1.0,0,98.728814,0,45.000000,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0,0,0,0,1,206500,4.045476,0.441656,3224.996127,360.0,0,0,1,497893.465696,0,0,0.0,4980.0,552,1,4.0,0,72.746457,0,37.732932,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0,1,0,0,0,406500,4.560000,0.200000,595.000000,360.0,1,0,0,508000.000000,0,0,0.0,9480.0,834,0,2.0,0,80.019685,0,46.000000,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0,0,0,0,0,456500,4.250000,0.681000,3224.996127,360.0,0,0,0,658000.000000,0,0,0.0,11880.0,587,0,3.0,1,69.376900,0,42.000000,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0,1,0,0,0,696500,4.000000,0.304200,0.000000,360.0,0,0,0,758000.000000,0,0,0.0,10440.0,602,1,1.0,1,91.886544,0,39.000000,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148665,0,0,0,0,0,436500,3.125000,0.257100,9960.000000,180.0,0,0,0,608000.000000,0,0,0.0,7860.0,659,1,4.0,0,71.792763,0,48.000000,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
148666,0,0,0,0,0,586500,5.190000,0.854400,0.000000,360.0,0,0,0,788000.000000,0,0,3.0,7140.0,569,0,1.0,1,74.428934,0,15.000000,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
148667,0,0,0,0,0,446500,3.125000,0.081600,1226.640000,180.0,0,0,0,728000.000000,0,0,0.0,6900.0,702,1,3.0,1,61.332418,0,49.000000,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148668,0,0,0,0,0,196500,3.500000,0.582400,4323.330000,180.0,0,0,0,278000.000000,0,0,0.0,7140.0,737,1,4.0,0,70.683453,0,29.000000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
148669,0,0,0,0,0,406500,4.375000,1.387100,6000.000000,240.0,0,0,0,558000.000000,0,0,0.0,7260.0,830,0,3.0,1,72.849462,0,44.000000,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
df.columns

Index(['loan_limit', 'approv_in_adv', 'Credit_Worthiness', 'open_credit',
       'business_or_commercial', 'loan_amount', 'rate_of_interest',
       'Interest_rate_spread', 'Upfront_charges', 'term', 'Neg_ammortization',
       'interest_only', 'lump_sum_payment', 'property_value',
       'construction_type', 'Secured_by', 'total_units', 'income',
       'Credit_Score', 'co-applicant_credit_type', 'age',
       'submission_of_application', 'LTV', 'Security_Type', 'dtir1', 'Status',
       'Gender_Joint', 'Gender_Male', 'Gender_Sex Not Available',
       'loan_type_type2', 'loan_type_type3', 'loan_purpose_p2',
       'loan_purpose_p3', 'loan_purpose_p4', 'occupancy_type_pr',
       'occupancy_type_sr', 'credit_type_CRIF', 'credit_type_EQUI',
       'credit_type_EXP', 'Region_North-East', 'Region_central',
       'Region_south'],
      dtype='object')

In [18]:
num_col = ['loan_amount','rate_of_interest','Interest_rate_spread','Upfront_charges', 'term','property_value','income', 'Credit_Score','LTV','dtir1']

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[num_col] = scaler.fit_transform(df[num_col])
df

,loan_limit,approv_in_adv,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,Neg_ammortization,interest_only,lump_sum_payment,property_value,construction_type,Secured_by,total_units,income,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Security_Type,dtir1,Status,Gender_Joint,Gender_Male,Gender_Sex Not Available,loan_type_type2,loan_type_type3,loan_purpose_p2,loan_purpose_p3,loan_purpose_p4,occupancy_type_pr,occupancy_type_sr,credit_type_CRIF,credit_type_EQUI,credit_type_EXP,Region_North-East,Region_central,Region_south
0,0,0,0,0,0,-1.166980,1.820924e-15,1.246439e-16,-1.633359e-16,0.425737,0,0,0,-1.113507,0,0,0.0,-0.829008,0.502357,0,1.0,0,6.858451e-01,0,7.529012e-01,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0,0,0,0,1,-0.677607,1.820924e-15,1.246439e-16,-1.633359e-16,0.425737,0,0,1,0.000000,0,0,0.0,-0.314189,-1.275413,1,4.0,0,-7.502356e-16,0,-7.361545e-16,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0,1,0,0,0,0.409890,1.054866e+00,-5.426102e-01,-9.446405e-01,0.425737,1,0,0,0.029623,0,0,0.0,0.400838,1.158234,0,2.0,0,1.919883e-01,0,8.565058e-01,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0,0,0,0,0,0.681764,4.193110e-01,5.374204e-01,-1.633359e-16,0.425737,0,0,0,0.469289,0,0,0.0,0.782185,-0.973365,0,3.0,1,-8.894476e-02,0,4.420876e-01,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0,1,0,0,0,1.986759,-9.323350e-02,-3.086410e-01,-1.158352e+00,0.425737,0,0,0,0.762399,0,0,0.0,0.553377,-0.843916,1,1.0,1,5.052326e-01,0,1.312740e-01,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148665,0,0,0,0,0,0.573014,-1.887139e+00,-4.143986e-01,2.419075e+00,-2.656410,0,0,0,0.322734,0,0,0.0,0.143428,-0.352008,1,4.0,0,-2.517425e-02,0,1.063715e+00,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
148666,0,0,0,0,0,1.388636,2.346478e+00,9.267703e-01,-1.158352e+00,0.425737,0,0,0,0.850332,0,0,3.0,0.029024,-1.128704,0,1.0,1,4.441161e-02,0,-2.355235e+00,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
148667,0,0,0,0,0,0.627389,-1.887139e+00,-8.084638e-01,-7.177684e-01,-2.656410,0,0,0,0.674466,0,0,0.0,-0.009111,0.019080,1,3.0,1,-3.012915e-01,0,1.167319e+00,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148668,0,0,0,0,0,-0.731981,-1.118323e+00,3.160253e-01,3.944989e-01,-2.656410,0,0,0,-0.644530,0,0,0.0,0.029024,0.321128,1,4.0,0,-5.445623e-02,0,-9.047715e-01,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
148669,0,0,0,0,0,0.409890,6.755833e-01,2.122887e+00,9.967243e-01,-1.629028,0,0,0,0.176178,0,0,0.0,0.048091,1.123714,0,3.0,1,2.718980e-03,0,6.492967e-01,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
df.to_csv("cleaned_Loan_Dataset.csv")